CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE IF NOT EXISTS audit_log(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),actor_id UUID,action VARCHAR(50) NOT NULL,details JSONB,created_at TIMESTAMPT@ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTSystem_config(key VARCHAR(100) PRIMARY KEY,value TEXT NOT NULL,description VARCHAR(500),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS fraud_alerts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID,severity VARCHAR(10) NOT NULL,alert_type VARCHAR(30) NOT NULL,message TEXT NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'OPEN',created_at TIMESTAMPT@ NOT NULL DEFAULT NOW());
INSERT INTO system_config(key,value,description) VALUES('p2p_fee_flat','2.50','P2P fee ETB'),ON CONFLICT(key) DO NOTHING;
