server:
  port: 8090
spring:
  application:
    name: gp-admin-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/admin_db}
    username: ${SPRING_DATASOURCE_USERNAME:globalpay}
    password: ${SPRING_DATASOURCE_PASSWORD:devpass}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
jwk:
  secret: SuperSecretKeyForGlobalPayJWT2024!
