server:
  port: 8081

spring:
  application:
    name: gp-auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:globalpay}
    password: ${SPRING_DATASOURCE_PASSWORD:devpass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
      timeout: 2000ms

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:SuperSecretKeyForGlobalPayJWT2024MustBe256BitsLongEnough!}
  expiry-ms: ${JWT_EXPIRY_MS:900000}
  refresh-expiry-ms: ${JWT_REFRESH_EXPIRY_MS:604800000}

otp:
  validity-seconds: 300
  max-attempts: 3
  mock-enabled: ${OTP_MOCK_ENABLED:true}

security:
  max-failed-pin-attempts: 5
  lockout-duration-minutes: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.globalpay: DEBUG
