import React, { createContext, useContext, useState, useCallback } from 'react';

type Language = 'en' | 'am';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  // Landing
  'landing.title': { en: 'Nisir Digital Experience', am: 'ኒሲር ዲጂታል ተሞክሮ' },
  'landing.subtitle': { en: 'Your trusted microfinance partner in Ethiopia', am: 'በኢትዮጵያ ውስጥ የታመነ ማይክሮ ፋይናንስ አጋርዎ' },
  'landing.retail': { en: 'For Customers', am: 'ለደንበኞች' },
  'landing.retail.desc': { en: 'Savings, loans, payments & more', am: 'ቁጠባ፣ ብድር፣ ክፍያዎች እና ተጨማሪ' },
  'landing.agency': { en: 'For Agents', am: 'ለወኪሎች' },
  'landing.agency.desc': { en: 'Cash services & customer onboarding', am: 'የጥሬ ገንዘብ አገልግሎቶች እና ደንበኛ ማስተናገድ' },
  'landing.merchant': { en: 'For Merchants', am: 'ለነጋዴዎች' },
  'landing.merchant.desc': { en: 'Accept payments & manage your business', am: 'ክፍያዎችን ይቀበሉ እና ንግድዎን ያስተዳድሩ' },
  'landing.admin': { en: 'For Staff', am: 'ለሰራተኞች' },
  'landing.admin.desc': { en: 'Administration & operations console', am: 'የአስተዳደር እና ኦፕሬሽን ኮንሶል' },
  'landing.ib': { en: 'Internet Banking', am: 'ኢንተርኔት ባንኪንግ' },
  'landing.ib.desc': { en: 'Full banking services online for individuals & SMEs', am: 'ለግለሰቦች እና ለ SME ሙሉ የባንክ አገልግሎት በመስመር ላይ' },

  // Common
  'common.home': { en: 'Home', am: 'መነሻ' },
  'common.accounts': { en: 'Accounts', am: 'ሂሳቦች' },
  'common.payments': { en: 'Payments', am: 'ክፍያዎች' },
  'common.loans': { en: 'Loans', am: 'ብድሮች' },
  'common.support': { en: 'Support', am: 'ድጋፍ' },
  'common.profile': { en: 'Profile', am: 'መገለጫ' },
  'common.settings': { en: 'Settings', am: 'ቅንብሮች' },
  'common.logout': { en: 'Logout', am: 'ውጣ' },
  'common.login': { en: 'Login', am: 'ግባ' },
  'common.back': { en: 'Back', am: 'ተመለስ' },
  'common.next': { en: 'Next', am: 'ቀጣይ' },
  'common.confirm': { en: 'Confirm', am: 'አረጋግጥ' },
  'common.cancel': { en: 'Cancel', am: 'ሰርዝ' },
  'common.search': { en: 'Search', am: 'ፈልግ' },
  'common.notifications': { en: 'Notifications', am: 'ማሳወቂያዎች' },
  'common.language': { en: 'Language', am: 'ቋንቋ' },
  'common.etb': { en: 'ETB', am: 'ብር' },
  'common.welcome': { en: 'Welcome', am: 'እንኳን ደህና መጡ' },
  'common.viewAll': { en: 'View All', am: 'ሁሉንም ይመልከቱ' },
  'common.save': { en: 'Save', am: 'አስቀምጥ' },
  'common.delete': { en: 'Delete', am: 'ሰርዝ' },
  'common.edit': { en: 'Edit', am: 'አርም' },
  'common.add': { en: 'Add', am: 'ጨምር' },
  'common.submit': { en: 'Submit', am: 'አስገባ' },
  'common.update': { en: 'Update', am: 'አዘምን' },
  'common.close': { en: 'Close', am: 'ዝጋ' },
  'common.processing': { en: 'Processing...', am: 'በመስራት ላይ...' },
  'common.loading': { en: 'Loading...', am: 'በመጫን ላይ...' },
  'common.noData': { en: 'No data available', am: 'ምንም መረጃ የለም' },
  'common.amount': { en: 'Amount', am: 'መጠን' },
  'common.status': { en: 'Status', am: 'ሁኔታ' },
  'common.date': { en: 'Date', am: 'ቀን' },
  'common.description': { en: 'Description', am: 'መግለጫ' },
  'common.reference': { en: 'Reference', am: 'ማጣቀሻ' },
  'common.type': { en: 'Type', am: 'ዓይነት' },
  'common.action': { en: 'Action', am: 'እርምጃ' },
  'common.actions': { en: 'Actions', am: 'እርምጃዎች' },
  'common.total': { en: 'Total', am: 'ጠቅላላ' },
  'common.fee': { en: 'Fee', am: 'ክፍያ' },
  'common.phone': { en: 'Phone', am: 'ስልክ' },
  'common.email': { en: 'Email', am: 'ኢሜይል' },
  'common.name': { en: 'Name', am: 'ስም' },
  'common.active': { en: 'Active', am: 'ንቁ' },
  'common.inactive': { en: 'Inactive', am: 'ንቁ ያልሆነ' },
  'common.pending': { en: 'Pending', am: 'በመጠባበቅ ላይ' },
  'common.completed': { en: 'Completed', am: 'ተጠናቋል' },
  'common.failed': { en: 'Failed', am: 'አልተሳካም' },
  'common.approved': { en: 'Approved', am: 'ተፈቅዷል' },
  'common.rejected': { en: 'Rejected', am: 'ተከልክሏል' },
  'common.export': { en: 'Export', am: 'ውጣ' },
  'common.download': { en: 'Download', am: 'አውርድ' },
  'common.generate': { en: 'Generate', am: 'አመንጭ' },
  'common.continue': { en: 'Continue', am: 'ቀጥል' },
  'common.individual': { en: 'Individual', am: 'ግለሰብ' },
  'common.corporate': { en: 'Corporate', am: 'ድርጅት' },
  'common.signOut': { en: 'Sign Out', am: 'ውጣ' },
  'common.messages': { en: 'Messages', am: 'መልእክቶች' },
  'common.collapse': { en: 'Collapse', am: 'አሳንስ' },
  'common.lastLogin': { en: 'Last login', am: 'ያለፈው ግቤት' },

  // Notifications
  'notifications.unread': { en: 'unread', am: 'ያልተነበበ' },
  'notifications.markAllRead': { en: 'Mark all read', am: 'ሁሉንም አንብብ' },
  'notifications.empty': { en: 'No notifications yet', am: 'ምንም ማሳወቂያዎች የሉም' },

  // Retail Portal
  'retail.myAccounts': { en: 'My Accounts & Wallets', am: 'የእኔ ሂሳቦች እና ዋሌቶች' },
  'retail.sendMoney': { en: 'Send Money', am: 'ገንዘብ ላክ' },
  'retail.payBills': { en: 'Pay Bills', am: 'ክፍያዎችን ይክፈሉ' },
  'retail.buyAirtime': { en: 'Buy Airtime', am: 'ኤርታይም ይግዙ' },
  'retail.loanApply': { en: 'Apply for Loan', am: 'ለብድር ያመልክቱ' },
  'retail.loanCalculator': { en: 'Loan Calculator', am: 'የብድር ማስያ' },
  'retail.transactions': { en: 'Transaction History', am: 'የግብይት ታሪክ' },
  'retail.savings': { en: 'Savings', am: 'ቁጠባ' },
  'retail.openAccount': { en: 'Open New Account', am: 'አዲስ ሂሳብ ክፈት' },
  'retail.linkWallet': { en: 'Link Mobile Wallet', am: 'ሞባይል ዋሌት አገናኝ' },
  'retail.availableBalance': { en: 'Available Balance', am: 'ያለ ቀሪ ሂሳብ' },
  'retail.profileComplete': { en: 'Profile Completeness', am: 'የመገለጫ ሙሉነት' },
  'retail.totalBalance': { en: 'Total Balance', am: 'ጠቅላላ ቀሪ ሂሳብ' },
  'retail.available': { en: 'Available', am: 'ያለ' },
  'retail.book': { en: 'Book', am: 'ቡክ' },
  'retail.blocked': { en: 'Blocked', am: 'የታገደ' },
  'retail.noTransactions': { en: 'No transactions yet', am: 'ግብይቶች የሉም' },
  'retail.upgradeKyc': { en: 'Upgrade KYC', am: 'ኬዋይሲ ያሻሽሉ' },

  // Agency Portal
  'agency.cashIn': { en: 'Cash In', am: 'ገንዘብ አስገባ' },
  'agency.cashOut': { en: 'Cash Out', am: 'ገንዘብ አውጣ' },
  'agency.newCustomer': { en: 'New Customer', am: 'አዲስ ደንበኛ' },
  'agency.loanRepay': { en: 'Loan Repayment', am: 'ብድር ክፍያ' },
  'agency.reports': { en: 'Reports', am: 'ሪፖርቶች' },
  'agency.float': { en: 'Float Balance', am: 'ፍሎት ቀሪ' },
  'agency.commission': { en: 'Commission', am: 'ኮሚሽን' },
  'agency.dailySummary': { en: "Today's Summary", am: 'የዛሬ ማጠቃለያ' },
  'agency.totalTransactions': { en: 'Total Transactions', am: 'ጠቅላላ ግብይቶች' },
  'agency.customers': { en: 'Customers', am: 'ደንበኞች' },
  'agency.airtime': { en: 'Airtime', am: 'ኤርታይም' },
  'agency.billPay': { en: 'Bill Payment', am: 'ክፍያ' },
  'agency.floatRequest': { en: 'Float Request', am: 'ፍሎት ጥያቄ' },
  'agency.profile': { en: 'Profile', am: 'መገለጫ' },
  'agency.onboarding': { en: 'Customer Onboarding', am: 'ደንበኛ ማስተናገድ' },
  'agency.recentTransactions': { en: 'Recent Transactions', am: 'የቅርብ ግብይቶች' },
  'agency.cashInTotal': { en: 'Cash In Total', am: 'ጠቅላላ ገንዘብ ማስገባት' },
  'agency.cashOutTotal': { en: 'Cash Out Total', am: 'ጠቅላላ ገንዘብ ማውጣት' },

  // Merchant Portal
  'merchant.todaysSales': { en: "Today's Sales", am: 'የዛሬ ሽያጮች' },
  'merchant.transactions': { en: 'Transactions', am: 'ግብይቶች' },
  'merchant.qrCodes': { en: 'QR Codes', am: 'ኪው.አር ኮዶች' },
  'merchant.qrReceive': { en: 'QR Receive', am: 'ኪው.አር ተቀበል' },
  'merchant.settlements': { en: 'Settlements', am: 'ሰትልመንቶች' },
  'merchant.disputes': { en: 'Disputes', am: 'አለመግባባቶች' },
  'merchant.outlets': { en: 'Outlets', am: 'ቅርንጫፎች' },
  'merchant.pendingSettlement': { en: 'Pending Settlement', am: 'በመጠባበቅ ላይ ያለ ሰትልመንት' },
  'merchant.nextSettlement': { en: 'Next Settlement', am: 'ቀጣይ ሰትልመንት' },
  'merchant.sales': { en: 'Sales', am: 'ሽያጮች' },
  'merchant.wallet': { en: 'Wallet', am: 'ዋሌት' },
  'merchant.vendors': { en: 'Vendors', am: 'አቅራቢዎች' },

  // Auth
  'auth.welcomeBack': { en: 'Welcome Back', am: 'እንኳን ደህና ተመለሱ' },
  'auth.createAccount': { en: 'Create Account', am: 'ሂሳብ ይፍጠሩ' },
  'auth.loginSubtitle': { en: 'Sign in to your Nisir account', am: 'ወደ ኒሲር ሂሳብዎ ይግቡ' },
  'auth.signupSubtitle': { en: 'Join Nisir microfinance', am: 'ኒሲር ማይክሮ ፋይናንስን ይቀላቀሉ' },
  'auth.firstName': { en: 'First Name', am: 'የመጀመሪያ ስም' },
  'auth.fatherName': { en: "Father's Name", am: 'የአባት ስም' },
  'auth.phone': { en: 'Phone Number', am: 'ስልክ ቁጥር' },
  'auth.email': { en: 'Email', am: 'ኢሜይል' },
  'auth.password': { en: 'Password', am: 'የይለፍ ቃል' },
  'auth.signUp': { en: 'Sign Up', am: 'ይመዝገቡ' },
  'auth.noAccount': { en: "Don't have an account?", am: 'ሂሳብ የለዎትም?' },
  'auth.hasAccount': { en: 'Already have an account?', am: 'ሂሳብ አለዎት?' },
  'auth.loginSuccess': { en: 'Login successful!', am: 'በተሳካ ሁኔታ ገብተዋል!' },
  'auth.signupSuccess': { en: 'Account created! Check your email.', am: 'ሂሳብ ተፈጥሯል! ኢሜይልዎን ያረጋግጡ።' },
  'auth.loginError': { en: 'Login failed', am: 'መግባት አልተሳካም' },
  'auth.signupError': { en: 'Registration failed', am: 'ምዝገባ አልተሳካም' },
  'auth.nameRequired': { en: 'Name is required', am: 'ስም ያስፈልጋል' },

  // Accounts & Wallets
  'accounts.copied': { en: 'Account number copied', am: 'የሂሳብ ቁጥር ተቀድቷል' },
  'accounts.notFound': { en: 'Account not found', am: 'ሂሳብ አልተገኘም' },
  'accounts.ownTransfer': { en: 'Own Transfer', am: 'የራስ ዝውውር' },
  'accounts.ownTransferDesc': { en: 'Move money between your accounts', am: 'ገንዘብ በሂሳቦችዎ መካከል ያዘዋውሩ' },
  'accounts.statement': { en: 'Statement', am: 'መግለጫ' },
  'accounts.settings': { en: 'Settings', am: 'ቅንብሮች' },
  'accounts.details': { en: 'Account Details', am: 'የሂሳብ ዝርዝር' },
  'accounts.type': { en: 'Account Type', am: 'የሂሳብ ዓይነት' },
  'accounts.currency': { en: 'Currency', am: 'ምንዛሬ' },
  'accounts.status': { en: 'Status', am: 'ሁኔታ' },
  'accounts.dailyLimit': { en: 'Daily Limit', am: 'ቀን ገደብ' },
  'accounts.monthlyLimit': { en: 'Monthly Limit', am: 'ወር ገደብ' },
  'accounts.interestRate': { en: 'Interest Rate', am: 'የወለድ መጠን' },
  'accounts.miniStatement': { en: 'Recent Transactions', am: 'የቅርብ ግብይቶች' },
  'accounts.noTransactions': { en: 'No transactions yet', am: 'ግብይቶች የሉም' },
  'accounts.statementDownloading': { en: 'Preparing your statement...', am: 'መግለጫዎን በማዘጋጀት ላይ...' },
  'accounts.openNew': { en: 'Open Account', am: 'ሂሳብ ክፈት' },
  'accounts.openNewDesc': { en: 'Choose an account product that fits your needs', am: 'ለፍላጎትዎ የሚመች የሂሳብ ምርት ይምረጡ' },
  'accounts.product.savings': { en: 'Savings Account', am: 'ቁጠባ ሂሳብ' },
  'accounts.product.savingsDesc': { en: 'Earn interest on your deposits', am: 'በተቀማጭ ገንዘብዎ ወለድ ያግኙ' },
  'accounts.product.current': { en: 'Current Account', am: 'ተንቀሳቃሽ ሂሳብ' },
  'accounts.product.currentDesc': { en: 'For daily business transactions', am: 'ለዕለት ንግድ ግብይቶች' },
  'accounts.product.wallet': { en: 'Digital Wallet', am: 'ዲጂታል ዋሌት' },
  'accounts.product.walletDesc': { en: 'Fast mobile payments', am: 'ፈጣን ሞባይል ክፍያዎች' },
  'accounts.nickname': { en: 'Account Nickname (optional)', am: 'የሂሳብ ቅጽል ስም (አማራጭ)' },
  'accounts.nicknamePlaceholder': { en: 'e.g. My Business Account', am: 'ለምሳሌ: የንግድ ሂሳቤ' },
  'accounts.createAccount': { en: 'Create Account', am: 'ሂሳብ ፍጠር' },
  'accounts.createSuccess': { en: 'Account created successfully!', am: 'ሂሳብ በተሳካ ሁኔታ ተፈጥሯል!' },
  'accounts.createError': { en: 'Failed to create account', am: 'ሂሳብ መፍጠር አልተሳካም' },
  'accounts.fromAccount': { en: 'From Account', am: 'ከሂሳብ' },
  'accounts.toAccount': { en: 'To Account', am: 'ወደ ሂሳብ' },
  'accounts.selectAccount': { en: 'Select account', am: 'ሂሳብ ይምረጡ' },
  'accounts.amount': { en: 'Amount', am: 'መጠን' },
  'accounts.reviewTransfer': { en: 'Review Transfer', am: 'ዝውውር ያረጋግጡ' },
  'accounts.confirmTransfer': { en: 'Confirm Transfer', am: 'ዝውውር ያረጋግጡ' },
  'accounts.transferSuccess': { en: 'Transfer Successful!', am: 'ዝውውር ተሳክቷል!' },
  'accounts.transferError': { en: 'Transfer failed', am: 'ዝውውር አልተሳካም' },
  'accounts.backToAccounts': { en: 'Back to Accounts', am: 'ወደ ሂሳቦች ተመለስ' },
  'accounts.transactionLimits': { en: 'Transaction Limits', am: 'የግብይት ገደቦች' },
  'accounts.saveLimits': { en: 'Save Limits', am: 'ገደቦች አስቀምጥ' },
  'accounts.settingsSaved': { en: 'Settings saved', am: 'ቅንብሮች ተቀምጠዋል' },
  'accounts.settingsError': { en: 'Failed to save settings', am: 'ቅንብሮች ማስቀመጥ አልተሳካም' },
  'accounts.freezeAccount': { en: 'Freeze Account', am: 'ሂሳብ ቀዝቅዝ' },
  'accounts.freezeDesc': { en: 'Temporarily block all transactions', am: 'ሁሉንም ግብይቶች ጊዜያዊ ያግዱ' },
  'accounts.freeze': { en: 'Freeze', am: 'ቀዝቅዝ' },
  'accounts.unfreeze': { en: 'Unfreeze', am: 'ክፈት' },
  'accounts.frozen': { en: 'Account frozen', am: 'ሂሳብ ቀዝቅዟል' },
  'accounts.unfrozen': { en: 'Account unfrozen', am: 'ሂሳብ ተከፍቷል' },
  'accounts.frozenWarning': { en: 'This account is frozen. All transactions are blocked until you unfreeze it.', am: 'ይህ ሂሳብ ቀዝቅዟል። እስኪከፍቱት ድረስ ሁሉም ግብይቶች ታግደዋል።' },
  'accounts.accountNumber': { en: 'Account Number', am: 'የሂሳብ ቁጥር' },
  'accounts.availableBalance': { en: 'Available Balance', am: 'ያለ ቀሪ ሂሳብ' },
  'accounts.ledgerBalance': { en: 'Ledger Balance', am: 'ሌጀር ቀሪ' },
  'accounts.blockedBalance': { en: 'Blocked', am: 'የታገደ' },
  'accounts.miniStatementTitle': { en: 'Mini Statement (Last 5)', am: 'ትንሽ መግለጫ (የመጨረሻ 5)' },

  // KYC
  'kyc.title': { en: 'Identity Verification', am: 'የማንነት ማረጋገጫ' },
  'kyc.chooseTier': { en: 'Choose Your KYC Level', am: 'የኬዋይሲ ደረጃ ይምረጡ' },
  'kyc.chooseTierDesc': { en: 'Higher tiers unlock more features and limits', am: 'ከፍ ያለ ደረጃ ተጨማሪ ባህሪያት ያስችላል' },
  'kyc.tier.basic': { en: 'Basic (Simplified)', am: 'መሰረታዊ (ቀለል ያለ)' },
  'kyc.tier.standard': { en: 'Standard (Full)', am: 'መደበኛ (ሙሉ)' },
  'kyc.tier.premium': { en: 'Premium (Enhanced)', am: 'ፕሪሚየም (የተሻሻለ)' },
  'kyc.completed': { en: 'Completed', am: 'ተጠናቋል' },
  'kyc.yourLevel': { en: 'Your KYC Level', am: 'የእርስዎ ኬዋይሲ ደረጃ' },
  'kyc.tier.unverified': { en: 'Unverified', am: 'ያልተረጋገጠ' },
  'kyc.upgradeToNext': { en: 'Upgrade to', am: 'ያሻሽሉ ወደ' },
  'kyc.maxTierReached': { en: 'You have the highest verification level', am: 'ከፍተኛው የማረጋገጫ ደረጃ ላይ ነዎት' },
  'kyc.upgrade.basic1': { en: 'Access digital wallet & basic transfers', am: 'ዲጂታል ዋሌት እና መሰረታዊ ዝውውሮች' },
  'kyc.upgrade.basic2': { en: 'Send up to 5,000 ETB per day', am: 'በቀን እስከ 5,000 ብር ላክ' },
  'kyc.upgrade.basic3': { en: 'Quick 2-minute setup — phone only', am: 'ፈጣን 2 ደቂቃ ማዋቀር — ስልክ ብቻ' },
  'kyc.upgrade.standard1': { en: 'Full payment services & bill payments', am: 'ሙሉ ክፍያ አገልግሎት እና ክፍያዎች' },
  'kyc.upgrade.standard2': { en: 'Apply for loans up to 50,000 ETB', am: 'እስከ 50,000 ብር ብድር ያመልክቱ' },
  'kyc.upgrade.standard3': { en: 'Transfer up to 50,000 ETB daily', am: 'በቀን እስከ 50,000 ብር ያዘዋውሩ' },
  'kyc.upgrade.premium1': { en: 'MSME & business account access', am: 'ኤምኤስኤምኢ እና የንግድ ሂሳብ' },
  'kyc.upgrade.premium2': { en: 'Unlimited daily transactions', am: 'ያልተገደበ ቀን ግብይቶች' },
  'kyc.upgrade.premium3': { en: 'Premium loan products & international transfers', am: 'ፕሪሚየም ብድር እና ዓለም አቀፍ ዝውውሮች' },
  'kyc.basic.feature1': { en: 'Basic wallet access', am: 'መሰረታዊ ዋሌት' },
  'kyc.basic.feature2': { en: 'Small transfers (up to 5,000 ETB/day)', am: 'ትንሽ ዝውውሮች (እስከ 5,000 ብር/ቀን)' },
  'kyc.basic.limits': { en: 'Daily: 5,000 ETB · Monthly: 50,000 ETB', am: 'ቀን: 5,000 ብር · ወር: 50,000 ብር' },
  'kyc.basic.requirements': { en: 'Requires: Name + Phone only', am: 'ያስፈልጋል: ስም + ስልክ ብቻ' },
  'kyc.standard.feature1': { en: 'Full payment services', am: 'ሙሉ ክፍያ አገልግሎት' },
  'kyc.standard.feature2': { en: 'Loan applications', am: 'የብድር ማመልከቻ' },
  'kyc.standard.feature3': { en: 'Higher transfers (up to 50,000 ETB/day)', am: 'ከፍ ያለ ዝውውር (እስከ 50,000 ብር/ቀን)' },
  'kyc.standard.limits': { en: 'Daily: 50,000 ETB · Monthly: 500,000 ETB', am: 'ቀን: 50,000 ብር · ወር: 500,000 ብር' },
  'kyc.standard.requirements': { en: 'Requires: ID document + Address', am: 'ያስፈልጋል: የመታወቂያ ሰነድ + አድራሻ' },
  'kyc.premium.feature1': { en: 'MSME & business accounts', am: 'ኤምኤስኤምኢ እና የንግድ ሂሳብ' },
  'kyc.premium.feature2': { en: 'International transfers', am: 'ዓለም አቀፍ ዝውውሮች' },
  'kyc.premium.feature3': { en: 'Premium loan products', am: 'ፕሪሚየም የብድር ምርቶች' },
  'kyc.premium.feature4': { en: 'Unlimited daily transactions', am: 'ያልተገደበ ቀን ግብይቶች' },
  'kyc.premium.limits': { en: 'Daily: 200,000 ETB · Monthly: Unlimited', am: 'ቀን: 200,000 ብር · ወር: ያልተገደበ' },
  'kyc.premium.requirements': { en: 'Requires: Selfie + Liveness + OCR verification', am: 'ያስፈልጋል: ሴልፊ + ቀጥታ ማረጋገጫ + OCR' },
  'kyc.personalDetails': { en: 'Personal Details', am: 'የግል መረጃ' },
  'kyc.firstName': { en: 'First Name', am: 'የመጀመሪያ ስም' },
  'kyc.fatherName': { en: "Father's Name", am: 'የአባት ስም' },
  'kyc.grandfatherName': { en: "Grandfather's Name", am: 'የአያት ስም' },
  'kyc.amharicNames': { en: 'Names in Amharic (ስም በአማርኛ)', am: 'ስም በአማርኛ' },
  'kyc.firstNameAm': { en: 'First Name (አማርኛ)', am: 'የመጀመሪያ ስም' },
  'kyc.fatherNameAm': { en: "Father's Name (አማርኛ)", am: 'የአባት ስም' },
  'kyc.grandfatherNameAm': { en: "Grandfather's (አማርኛ)", am: 'የአያት ስም' },
  'kyc.gender': { en: 'Gender', am: 'ጾታ' },
  'kyc.male': { en: 'Male', am: 'ወንድ' },
  'kyc.female': { en: 'Female', am: 'ሴት' },
  'kyc.dob': { en: 'Date of Birth', am: 'የልደት ቀን' },
  'kyc.maritalStatus': { en: 'Marital Status', am: 'የጋብቻ ሁኔታ' },
  'kyc.single': { en: 'Single', am: 'ያላገባ' },
  'kyc.married': { en: 'Married', am: 'ያገባ' },
  'kyc.divorced': { en: 'Divorced', am: 'የተፋታ' },
  'kyc.widowed': { en: 'Widowed', am: 'ባል/ሚስት የሞተበት' },
  'kyc.phone': { en: 'Phone Number', am: 'ስልክ ቁጥር' },
  'kyc.select': { en: 'Select', am: 'ይምረጡ' },
  'kyc.nameRequired': { en: 'First name and father name are required', am: 'የመጀመሪያ ስም እና የአባት ስም ያስፈልጋል' },
  'kyc.phoneRequired': { en: 'Phone number is required', am: 'ስልክ ቁጥር ያስፈልጋል' },
  'kyc.addressDetails': { en: 'Address Details', am: 'የአድራሻ ዝርዝር' },
  'kyc.region': { en: 'Region', am: 'ክልል' },
  'kyc.selectRegion': { en: 'Select Region', am: 'ክልል ይምረጡ' },
  'kyc.woreda': { en: 'Woreda', am: 'ወረዳ' },
  'kyc.kebele': { en: 'Kebele', am: 'ቀበሌ' },
  'kyc.houseNumber': { en: 'House Number', am: 'የቤት ቁጥር' },
  'kyc.regionRequired': { en: 'Region is required', am: 'ክልል ያስፈልጋል' },
  'kyc.documentUpload': { en: 'ID Document Upload', am: 'የመታወቂያ ሰነድ ስቀል' },
  'kyc.documentType': { en: 'Document Type', am: 'የሰነድ ዓይነት' },
  'kyc.nationalId': { en: 'National ID (Fayda)', am: 'ብሔራዊ መታወቂያ (ፋይዳ)' },
  'kyc.passport': { en: 'Passport', am: 'ፓስፖርት' },
  'kyc.drivingLicense': { en: 'Driving License', am: 'የመንጃ ፈቃድ' },
  'kyc.kebeleId': { en: 'Kebele ID', am: 'የቀበሌ መታወቂያ' },
  'kyc.documentNumber': { en: 'Document Number', am: 'የሰነድ ቁጥር' },
  'kyc.enterDocNumber': { en: 'Enter document number', am: 'የሰነድ ቁጥር ያስገቡ' },
  'kyc.frontSide': { en: 'Front Side', am: 'ፊት ገጽ' },
  'kyc.backSide': { en: 'Back Side', am: 'ኋላ ገጽ' },
  'kyc.tapToUpload': { en: 'Tap to upload or take photo', am: 'ለመስቀል ወይም ፎቶ ለማንሳት ይጫኑ' },
  'kyc.docNumberRequired': { en: 'Document number is required', am: 'የሰነድ ቁጥር ያስፈልጋል' },
  'kyc.frontImageRequired': { en: 'Front side image is required', am: 'የፊት ገጽ ምስል ያስፈልጋል' },
  'kyc.selfieVerification': { en: 'Selfie & Liveness Verification', am: 'ሴልፊ እና ቀጥታ ማረጋገጫ' },
  'kyc.selfieDesc': { en: 'Take a clear selfie for face matching and liveness detection', am: 'ለፊት ማዛመድ እና ቀጥታ ማረጋገጫ ግልጽ ሴልፊ ያንሱ' },
  'kyc.livenessCheck': { en: 'Liveness Check Instructions', am: 'የቀጥታ ማረጋገጫ መመሪያ' },
  'kyc.liveness1': { en: 'Hold your face clearly in frame', am: 'ፊትዎን በግልጽ ያስቀምጡ' },
  'kyc.liveness2': { en: 'Ensure good lighting', am: 'ጥሩ ብርሃን ያረጋግጡ' },
  'kyc.liveness3': { en: 'Remove sunglasses or masks', am: 'የፀሐይ መነፅር ወይም ጭንብል ያስወግዱ' },
  'kyc.takeSelfie': { en: 'Tap to take selfie', am: 'ሴልፊ ለማንሳት ይጫኑ' },
  'kyc.openCamera': { en: 'Open Camera', am: 'ካሜራ ክፈት' },
  'kyc.retake': { en: 'Retake', am: 'እንደገና አንሳ' },
  'kyc.tryAgain': { en: 'Try Again', am: 'እንደገና ሞክር' },
  'kyc.cameraPermissionDenied': { en: 'Camera permission denied. Please allow camera access.', am: 'የካሜራ ፈቃድ ተከልክሏል። እባክዎ ካሜራ ያስችሉ።' },
  'kyc.cameraError': { en: 'Could not access camera. Please try again.', am: 'ካሜራ መክፈት አልተቻለም። እንደገና ይሞክሩ።' },
  'kyc.orUploadSelfie': { en: 'Or upload a photo instead', am: 'ወይም ፎቶ ይስቀሉ' },
  'kyc.uploadPhoto': { en: 'Upload Photo', am: 'ፎቶ ስቀል' },
  'kyc.needBothImages': { en: 'Both selfie and ID document are needed', am: 'ሴልፊ እና መታወቂያ ሁለቱም ያስፈልጋሉ' },
  'kyc.runVerification': { en: 'Run AI Verification', am: 'AI ማረጋገጫ ያስጀምሩ' },
  'kyc.verifying': { en: 'Verifying...', am: 'በማረጋገጥ ላይ...' },
  'kyc.verificationPassed': { en: 'Verification passed!', am: 'ማረጋገጫ ተሳክቷል!' },
  'kyc.verificationFailed': { en: 'Verification failed. Please try again.', am: 'ማረጋገጫ አልተሳካም። እንደገና ይሞክሩ።' },
  'kyc.completeVerification': { en: 'Please complete verification first', am: 'እባክዎ ማረጋገጫ ያጠናቅቁ' },
  'kyc.verified': { en: 'Verified', am: 'ተረጋግጧል' },
  'kyc.notVerified': { en: 'Not Verified', am: 'አልተረጋገጠም' },
  'kyc.liveness': { en: 'Liveness', am: 'ቀጥታ' },
  'kyc.faceMatch': { en: 'Face Match', am: 'ፊት ማዛመድ' },
  'kyc.confidence': { en: 'Confidence', am: 'ዓመኔታ' },
  'kyc.ocrExtracted': { en: 'OCR Extracted Data', am: 'OCR የተወሰደ መረጃ' },
  'kyc.name': { en: 'Name', am: 'ስም' },
  'kyc.docNum': { en: 'Document No.', am: 'ሰነድ ቁ.' },
  'kyc.reviewTitle': { en: 'Review & Confirm', am: 'ይገምግሙ እና ያረጋግጡ' },
  'kyc.tierSelected': { en: 'KYC tier selected', am: 'የኬዋይሲ ደረጃ ተመርጧል' },
  'kyc.uploaded': { en: 'Uploaded', am: 'ተሰቅሏል' },
  'kyc.captured': { en: 'Captured', am: 'ተነስቷል' },
  'kyc.passed': { en: 'Passed', am: 'ያለፈ' },
  'kyc.selfie': { en: 'Selfie', am: 'ሴልፊ' },
  'kyc.submitting': { en: 'Submitting...', am: 'በማስገባት ላይ...' },
  'kyc.submitKyc': { en: 'Submit KYC', am: 'ኬዋይሲ ያስገቡ' },
  'kyc.submitSuccess': { en: 'KYC submitted successfully!', am: 'ኬዋይሲ በተሳካ ሁኔታ ተልኳል!' },
  'kyc.submitError': { en: 'Failed to submit KYC', am: 'ኬዋይሲ ማስገባት አልተሳካም' },

  // Transfer & Payment Hub
  'transfer.walletTransfers': { en: 'Wallet Transfers', am: 'የዋሌት ዝውውሮች' },
  'transfer.bankServices': { en: 'Bank Services', am: 'የባንክ አገልግሎቶች' },
  'transfer.mnoWallets': { en: 'MNO Wallets', am: 'የMNO ዋሌቶች' },
  'transfer.billsAndTopup': { en: 'Bills & Top-up', am: 'ክፍያዎች እና ሙላ' },
  'transfer.nisirToNisir': { en: 'Nisir to Nisir', am: 'ኒሲር ወደ ኒሲር' },
  'transfer.nisirToNisirDesc': { en: 'Send to any Nisir wallet instantly', am: 'ወደ ማንኛውም ኒሲር ዋሌት በቅጽበት ላክ' },
  'transfer.p2pDesc': { en: 'Transfer to any Nisir user by phone', am: 'በስልክ ቁጥር ወደ ማንኛውም ተጠቃሚ ላክ' },
  'transfer.bankDeposit': { en: 'Bank Deposit / Withdraw', am: 'ከባንክ አስገባ / አውጣ' },
  'transfer.bankDepositDesc': { en: 'Add funds from any Ethiopian bank', am: 'ከማንኛውም የኢትዮጵያ ባንክ ገንዘብ አስገባ' },
  'transfer.sendToMno': { en: 'Send to MNO Wallet', am: 'ወደ MNO ዋሌት ላክ' },
  'transfer.sendToMnoDesc': { en: 'Telebirr, M-PESA, CBE Birr, Amole & more', am: 'ቴሌብር፣ ኤም-ፔሳ፣ ሲቢኢ ብር፣ አሞሌ እና ተጨማሪ' },
  'transfer.receiveFromMno': { en: 'Receive from MNO', am: 'ከMNO ተቀበል' },
  'transfer.receiveFromMnoDesc': { en: 'Pull funds from Telebirr, M-PESA & others', am: 'ከቴሌብር፣ ኤም-ፔሳ እና ሌሎች ገንዘብ ተቀበል' },
  'transfer.billsDesc': { en: 'Utilities, telecom, government, entertainment', am: 'መገልገያ፣ ቴሌኮም፣ መንግስት' },
  'transfer.airtimeDesc': { en: 'Ethio Telecom top-up', am: 'ኢትዮ ቴሌኮም ሙላ' },
  'transfer.selectBank': { en: 'Select Bank', am: 'ባንክ ይምረጡ' },
  'transfer.chooseBank': { en: 'Choose your bank', am: 'ባንክዎን ይምረጡ' },
  'transfer.bankAccountNumber': { en: 'Bank Account Number', am: 'የባንክ ሂሳብ ቁጥር' },
  'transfer.depositTo': { en: 'Deposit to Nisir Account', am: 'ወደ ኒሲር ሂሳብ አስገባ' },
  'transfer.depositSuccess': { en: 'Deposit Successful!', am: 'ተቀማጭ ተሳክቷል!' },
  'transfer.deposited': { en: 'deposited to your account', am: 'ወደ ሂሳብዎ ገብቷል' },
  'transfer.bankAccount': { en: 'Bank Account', am: 'የባንክ ሂሳብ' },
  'transfer.selectOperator': { en: 'Select Operator', am: 'ኦፕሬተር ይምረጡ' },
  'transfer.operator': { en: 'Operator', am: 'ኦፕሬተር' },
  'transfer.phone': { en: 'Phone', am: 'ስልክ' },
  'transfer.fee': { en: 'Fee', am: 'ክፍያ' },
  'transfer.total': { en: 'Total', am: 'ጠቅላላ' },
  'transfer.recipient': { en: 'Recipient', am: 'ተቀባይ' },
  'transfer.recipientPhone': { en: 'Recipient Phone', am: 'የተቀባይ ስልክ' },
  'transfer.senderPhone': { en: 'Sender Phone', am: 'የላኪ ስልክ' },
  'transfer.recipientNisirPhone': { en: 'Recipient Nisir Phone', am: 'የተቀባይ ኒሲር ስልክ' },
  'transfer.network': { en: 'Network', am: 'ኔትዎርክ' },
  'transfer.sentSuccess': { en: 'Transfer Sent!', am: 'ዝውውር ተልኳል!' },
  'transfer.receiveSuccess': { en: 'Funds Received!', am: 'ገንዘብ ተቀብሏል!' },

  // Agent Banking (Customer-side)
  'agent.selectNearbyAgent': { en: 'Select Nearby Agent', am: 'ቅርብ ወኪል ይምረጡ' },
  'agent.selectAgentDesc': { en: 'Choose an agent to deposit cash', am: 'ገንዘብ ለማስገባት ወኪል ይምረጡ' },
  'agent.selectAgentCashOut': { en: 'Choose an agent to withdraw cash', am: 'ገንዘብ ለማውጣት ወኪል ይምረጡ' },
  'agent.notAvailable': { en: 'Agent is currently offline', am: 'ወኪል አሁን ላይ አይደለም' },
  'agent.offline': { en: 'Offline', am: 'ከመስመር ውጭ' },
  'agent.cashReady': { en: 'Cash Ready', am: 'ገንዘብ ዝግጁ' },
  'agent.enterCashInAmount': { en: 'Enter Deposit Amount', am: 'የተቀማጭ መጠን ያስገቡ' },
  'agent.enterCashOutAmount': { en: 'Enter Withdrawal Amount', am: 'የማውጣት መጠን ያስገቡ' },
  'agent.depositAmount': { en: 'Deposit Amount', am: 'የተቀማጭ መጠን' },
  'agent.withdrawAmount': { en: 'Withdrawal Amount', am: 'የማውጣት መጠን' },
  'agent.enterValidAmount': { en: 'Enter a valid amount', am: 'ትክክለኛ መጠን ያስገቡ' },
  'agent.insufficientBalance': { en: 'Insufficient balance', am: 'ቀሪ ሂሳብ በቂ አይደለም' },
  'agent.agentLowCash': { en: 'Agent has insufficient cash', am: 'ወኪል በቂ ገንዘብ የለውም' },
  'agent.depositTo': { en: 'Deposit to Account', am: 'ወደ ሂሳብ አስገባ' },
  'agent.debitFrom': { en: 'Debit from Account', am: 'ከሂሳብ አውጣ' },
  'agent.generateCode': { en: 'Generate Deposit Code', am: 'የተቀማጭ ኮድ ያመንጩ' },
  'agent.depositCode': { en: 'Deposit Code', am: 'የተቀማጭ ኮድ' },
  'agent.showCodeToAgent': { en: 'Show this code to the agent', am: 'ይህን ኮድ ለወኪሉ ያሳዩ' },
  'agent.yourDepositCode': { en: 'Your Deposit Code', am: 'የእርስዎ ተቀማጭ ኮድ' },
  'agent.codeCopied': { en: 'Code copied!', am: 'ኮድ ተቀድቷል!' },
  'agent.copyCode': { en: 'Copy Code', am: 'ኮድ ቅዳ' },
  'agent.agentName': { en: 'Agent', am: 'ወኪል' },
  'agent.outlet': { en: 'Outlet', am: 'ቅርንጫፍ' },
  'agent.codeExpiry': { en: 'Code expires in 15 minutes', am: 'ኮድ በ15 ደቂቃ ያበቃል' },
  'agent.agentConfirmed': { en: 'Agent Confirmed — Proceed', am: 'ወኪል አረጋግጧል — ቀጥል' },
  'agent.otpVerification': { en: 'OTP Verification', am: 'የOTP ማረጋገጫ' },
  'agent.otpSentDesc': { en: 'Enter the 6-digit OTP sent to your phone', am: 'ወደ ስልክዎ የተላከውን 6 አሃዝ OTP ያስገቡ' },
  'agent.enterOtpCode': { en: 'Enter verification code', am: 'የማረጋገጫ ኮድ ያስገቡ' },
  'agent.enterOtp': { en: 'Please enter the full OTP', am: 'እባክዎ ሙሉ OTP ያስገቡ' },
  'agent.invalidOtp': { en: 'Invalid OTP. Try again.', am: 'ልክ ያልሆነ OTP። እንደገና ይሞክሩ።' },
  'agent.otpHint': { en: 'For demo: enter any 6 digits', am: 'ለማሳያ: ማንኛውንም 6 አሃዞች ያስገቡ' },
  'agent.cashInSuccess': { en: 'Cash-In Successful!', am: 'ገንዘብ ማስገባት ተሳክቷል!' },
  'agent.depositedToAccount': { en: 'deposited to your account', am: 'ወደ ሂሳብዎ ገብቷል' },
  'agent.reference': { en: 'Reference', am: 'ማጣቀሻ' },
  'agent.transactionFailed': { en: 'Transaction failed', am: 'ግብይት አልተሳካም' },
  'agent.reviewWithdrawal': { en: 'Review Withdrawal', am: 'ማውጣት ያረጋግጡ' },
  'agent.reviewDetails': { en: 'Review Details', am: 'ዝርዝር ይገምግሙ' },
  'agent.confirmDetails': { en: 'Confirm the transaction details', am: 'የግብይት ዝርዝሮችን ያረጋግጡ' },
  'agent.proceedToVerify': { en: 'Proceed to Verify', am: 'ለማረጋገጥ ቀጥል' },
  'agent.withdraw': { en: 'Withdraw', am: 'አውጣ' },
  'agent.cashOutApproved': { en: 'Withdrawal Approved!', am: 'ማውጣት ጸድቋል!' },
  'agent.showWithdrawalCode': { en: 'Show this code to receive cash from agent', am: 'ከወኪሉ ገንዘብ ለመቀበል ይህን ኮድ ያሳዩ' },
  'agent.withdrawalCode': { en: 'Withdrawal Code', am: 'የማውጣት ኮድ' },
  'agent.cashCollected': { en: 'Cash Collected ✓', am: 'ገንዘብ ተሰብስቧል ✓' },
  'agent.cashOutComplete': { en: 'Cash-Out Complete!', am: 'ገንዘብ ማውጣት ተጠናቋል!' },
  'agent.withdrawnSuccessfully': { en: 'withdrawn successfully', am: 'በተሳካ ሁኔታ ወጥቷል' },

  // Admin
  'admin.dashboard': { en: 'Dashboard', am: 'ዳሽቦርድ' },
  'admin.customers': { en: 'Customers', am: 'ደንበኞች' },
  'admin.agents': { en: 'Agents', am: 'ወኪሎች' },
  'admin.merchants': { en: 'Merchants', am: 'ነጋዴዎች' },
  'admin.products': { en: 'Products', am: 'ምርቶች' },
  'admin.reconciliation': { en: 'Reconciliation', am: 'ማስታረቅ' },
  'admin.security': { en: 'Security', am: 'ደህንነት' },
  'admin.architecture': { en: 'Architecture', am: 'አርክቴክቸር' },
  'admin.config': { en: 'Configuration', am: 'ውቅር' },
  'admin.reports': { en: 'Reports & Analytics', am: 'ሪፖርቶች እና ትንተና' },
  'admin.workflows': { en: 'Workflows', am: 'የስራ ፍሰቶች' },
  'admin.kycReview': { en: 'KYC Review', am: 'ኬዋይሲ ግምገማ' },
  'admin.compliance': { en: 'Compliance', am: 'ተገዢነት' },
  'admin.transactions': { en: 'Transactions', am: 'ግብይቶች' },
  'admin.accounting': { en: 'Accounting', am: 'ሂሳብ አያያዝ' },
  'admin.integrations': { en: 'Integrations', am: 'ውህደቶች' },
  'admin.amlCompliance': { en: 'AML Compliance', am: 'የገንዘብ ልቀቅ ቁጥጥር' },
  'admin.support': { en: 'Support', am: 'ድጋፍ' },
  'admin.loanManagement': { en: 'Loan Management', am: 'የብድር አስተዳደር' },
  'admin.corporateOnboarding': { en: 'Corporate Onboarding', am: 'ድርጅት ማስተናገድ' },
  'admin.operationsConsole': { en: 'Operations Console', am: 'ኦፕሬሽን ኮንሶል' },
  'admin.totalTxns': { en: 'Total Txns', am: 'ጠቅላላ ግብይቶች' },
  'admin.credits': { en: 'Credits', am: 'ብድሮች' },
  'admin.debits': { en: 'Debits', am: 'ወጪዎች' },
  'admin.allTypes': { en: 'All Types', am: 'ሁሉም ዓይነቶች' },
  'admin.allStatus': { en: 'All Status', am: 'ሁሉም ሁኔታ' },
  'admin.searchPlaceholder': { en: 'Search by reference, description...', am: 'በማጣቀሻ፣ መግለጫ ፈልግ...' },
  // Admin Layout & Dashboard Content
  'admin.nisirAdmin': { en: 'Nisir Admin', am: 'ኒሲር አስተዳዳሪ' },
  'admin.configuration': { en: 'Configuration', am: 'ውቅር' },
  'admin.totalCustomers': { en: 'Total Customers', am: 'ጠቅላላ ደንበኞች' },
  'admin.activeAccounts': { en: 'Active Accounts', am: 'ንቁ ሂሳቦች' },
  'admin.totalTransactions': { en: 'Total Transactions', am: 'ጠቅላላ ግብይቶች' },
  'admin.volumeETB': { en: 'Volume (ETB)', am: 'መጠን (ብር)' },
  'admin.pendingKyc': { en: 'Pending KYC', am: 'በመጠባበቅ ላይ ያለ ኬዋይሲ' },
  'admin.openTickets': { en: 'Open Tickets', am: 'ክፍት ጥያቄዎች' },
  'admin.dailyTxnVolume': { en: 'Daily Transaction Volume (ETB)', am: 'ዕለታዊ የግብይት መጠን (ብር)' },
  'admin.txnsByType': { en: 'Transactions by Type', am: 'ግብይቶች በአይነት' },
  'admin.kycTierDist': { en: 'KYC Tier Distribution', am: 'ኬዋይሲ ደረጃ ስርጭት' },
  'admin.loanPortfolioByProduct': { en: 'Loan Portfolio by Product', am: 'የብድር ፖርትፎሊዮ በምርት' },
  'admin.recentTransactions': { en: 'Recent Transactions', am: 'የቅርብ ጊዜ ግብይቶች' },
  'admin.reference': { en: 'Reference', am: 'ማጣቀሻ' },
  'admin.type': { en: 'Type', am: 'ዓይነት' },
  'admin.amount': { en: 'Amount', am: 'መጠን' },
  'admin.direction': { en: 'Direction', am: 'አቅጣጫ' },
  'admin.status': { en: 'Status', am: 'ሁኔታ' },
  'admin.date': { en: 'Date', am: 'ቀን' },
  'admin.channel': { en: 'Channel', am: 'ቻናል' },
  'admin.searchCustomers': { en: 'Search customers...', am: 'ደንበኞችን ፈልግ...' },
  'admin.all': { en: 'All', am: 'ሁሉም' },
  'admin.pending': { en: 'Pending', am: 'በመጠባበቅ' },
  'admin.simplified': { en: 'Simplified', am: 'ቀላል' },
  'admin.full': { en: 'Full', am: 'ሙሉ' },
  'admin.rejected': { en: 'Rejected', am: 'ውድቅ' },
  'admin.email': { en: 'Email', am: 'ኢሜይል' },
  'admin.phone': { en: 'Phone', am: 'ስልክ' },
  'admin.kycTier': { en: 'KYC Tier', am: 'ኬዋይሲ ደረጃ' },
  'admin.region': { en: 'Region', am: 'ክልል' },
  'admin.profileComplete': { en: 'Profile Complete', am: 'ፕሮፋይል ተጠናቋል' },
  'admin.joined': { en: 'Joined', am: 'ተቀላቀለ' },
  'admin.close': { en: 'Close', am: 'ዝጋ' },
  'admin.volumeByType': { en: 'Volume by Transaction Type (ETB)', am: 'በግብይት ዓይነት መጠን (ብር)' },
  'admin.transfer': { en: 'Transfer', am: 'ዝውውር' },
  'admin.deposit': { en: 'Deposit', am: 'ተቀማጭ' },
  'admin.withdrawal': { en: 'Withdrawal', am: 'ማውጫ' },
  'admin.billPayment': { en: 'Bill Payment', am: 'ቢል ክፍያ' },
  'admin.airtime': { en: 'Airtime', am: 'የአየር ሰዓት' },
  'admin.loanRepayment': { en: 'Loan Repayment', am: 'ብድር ክፍያ' },
  'admin.completed': { en: 'Completed', am: 'ተጠናቋል' },
  'admin.failed': { en: 'Failed', am: 'ያልተሳካ' },
  'admin.totalVolume': { en: 'Total volume', am: 'ጠቅላላ መጠን' },
  'admin.approved': { en: 'Approved', am: 'ፀድቋል' },
  'admin.review': { en: 'Review', am: 'ግምገማ' },
  'admin.documentType': { en: 'Document Type', am: 'ሰነድ ዓይነት' },
  'admin.documentNumber': { en: 'Document Number', am: 'ሰነድ ቁጥር' },
  'admin.submitted': { en: 'Submitted', am: 'ቀርቧል' },
  'admin.frontImage': { en: 'Front Image', am: 'ፊት ምስል' },
  'admin.backImage': { en: 'Back Image', am: 'ኋላ ምስል' },
  'admin.rejectionReasonPlaceholder': { en: 'Rejection reason (required only for rejection)', am: 'ውድቅ ምክንያት (ለውድቅ ብቻ ያስፈልጋል)' },
  'admin.approve': { en: 'Approve', am: 'አፅድቅ' },
  'admin.reject': { en: 'Reject', am: 'ውድቅ አድርግ' },
  'admin.noDocsFound': { en: 'No documents found', am: 'ምንም ሰነዶች አልተገኙም' },
  'admin.ticketStatus': { en: 'Ticket Status', am: 'ጥያቄ ሁኔታ' },
  'admin.open': { en: 'Open', am: 'ክፍት' },
  'admin.inProgress': { en: 'In Progress', am: 'በሂደት ላይ' },
  'admin.resolved': { en: 'Resolved', am: 'ተፈትቷል' },
  'admin.closed': { en: 'Closed', am: 'ተዘግቷል' },
  'admin.total': { en: 'Total', am: 'ጠቅላላ' },
  'admin.searchTickets': { en: 'Search tickets...', am: 'ጥያቄዎችን ፈልግ...' },
  'admin.category': { en: 'Category', am: 'ምድብ' },
  'admin.priority': { en: 'Priority', am: 'ቅድሚያ' },
  'admin.created': { en: 'Created', am: 'ተፈጥሮ' },
  'admin.resolution': { en: 'Resolution', am: 'መፍትሔ' },
  'admin.enterResolution': { en: 'Enter resolution...', am: 'መፍትሔ ያስገቡ...' },
  'admin.resolve': { en: 'Resolve', am: 'ፍታ' },
  'admin.escalate': { en: 'Escalate', am: 'አሳድግ' },
  'admin.noDescription': { en: 'No description provided.', am: 'ምንም መግለጫ አልቀረበም።' },
  'admin.totalMerchants': { en: 'Total Merchants', am: 'ጠቅላላ ነጋዴዎች' },
  'admin.active': { en: 'Active', am: 'ንቁ' },
  'admin.monthlyVolETB': { en: 'Monthly Vol (ETB)', am: 'ወርሃዊ መጠን (ብር)' },
  'admin.monthlyVolumeByMerchant': { en: 'Monthly Volume by Merchant (k ETB)', am: 'በነጋዴ ወርሃዊ መጠን (ሺ ብር)' },
  'admin.wallet': { en: 'Wallet', am: 'ዋሌት' },
  'admin.platformGrowthTrends': { en: 'Platform Growth Trends (6 Months)', am: 'የመድረክ ዕድገት አዝማሚያዎች (6 ወር)' },
  'admin.revenueBreakdown': { en: 'Revenue Breakdown (ETB)', am: 'ገቢ ትንተና (ብር)' },
  'admin.loanPortfolioDist': { en: 'Loan Portfolio Distribution', am: 'የብድር ፖርትፎሊዮ ስርጭት' },
  'admin.txnChannels': { en: 'Transaction Channels', am: 'የግብይት ቻናሎች' },
  'admin.topAgentPerformance': { en: 'Top Agent Performance (ETB)', am: 'ከፍተኛ ወኪል አፈፃፀም (ብር)' },
  'admin.customerDistByRegion': { en: 'Customer Distribution by Region', am: 'ደንበኞች ስርጭት በክልል' },
  'admin.totalDisbursed': { en: 'Total Disbursed', am: 'ጠቅላላ የተለቀቀ' },
  'admin.outstanding': { en: 'Outstanding', am: 'ያልተከፈለ' },
  'admin.parRatio': { en: 'PAR Ratio', am: 'ፒኤአር ምጣኔ' },
  'admin.atRisk': { en: 'At Risk', am: 'አደጋ ላይ' },
  'admin.healthy': { en: 'Healthy', am: 'ጤናማ' },
  'admin.activeLoans': { en: 'Active Loans', am: 'ንቁ ብድሮች' },
  'admin.loanPipeline': { en: 'Loan Pipeline', am: 'የብድር መስመር' },
  'admin.portfolio': { en: 'Portfolio', am: 'ፖርትፎሊዮ' },
  'admin.waivers': { en: 'Waivers', am: 'ነፃ ማድረጊያ' },
  'admin.cbsEvents': { en: 'CBS Events', am: 'ሲቢኤስ ክስተቶች' },
  'admin.customer': { en: 'Customer', am: 'ደንበኛ' },
  'admin.product': { en: 'Product', am: 'ምርት' },
  'admin.rate': { en: 'Rate', am: 'ምጣኔ' },
  'admin.tenor': { en: 'Tenor', am: 'ጊዜ' },
  'admin.actions': { en: 'Actions', am: 'ድርጊቶች' },
  'admin.appFunnel': { en: 'Application Funnel', am: 'ማመልከቻ ማጣሪያ' },
  'admin.totalSubmitted': { en: 'Total Submitted', am: 'ጠቅላላ የቀረበ' },
  'admin.pendingReview': { en: 'Pending Review', am: 'ግምገማ በመጠባበቅ' },
  'admin.loanStatusDist': { en: 'Loan Status Distribution', am: 'የብድር ሁኔታ ስርጭት' },
  'admin.disbursementByProduct': { en: 'Disbursement by Product', am: 'ግልጋሎት በምርት' },
  'admin.portfolioAging': { en: 'Portfolio Aging Analysis', am: 'የፖርትፎሊዮ ዕድሜ ትንተና' },
  'admin.current': { en: 'Current', am: 'ወቅታዊ' },
  'admin.watch': { en: 'Watch', am: 'ክትትል' },
  'admin.substandard': { en: 'Substandard', am: 'ከደረጃ በታች' },
  'admin.doubtful': { en: 'Doubtful', am: 'አጠራጣሪ' },
  'admin.loss': { en: 'Loss', am: 'ኪሳራ' },
  'admin.approveWaiver': { en: 'Approve Waiver', am: 'ነፃ ማድረጊያ አፅድቅ' },
  'admin.noWaiverRequests': { en: 'No waiver requests', am: 'ምንም ጥያቄ የለም' },
  'admin.loanProductConfigs': { en: 'Loan Product Configurations', am: 'የብድር ምርት ውቅሮች' },
  'admin.registerCorporate': { en: 'Register Corporate', am: 'ድርጅት መዝግብ' },
  'admin.totalCorporates': { en: 'Total Corporates', am: 'ጠቅላላ ድርጅቶች' },
  'admin.totalUsers': { en: 'Total Users', am: 'ጠቅላላ ተጠቃሚዎች' },
  'admin.rbacRoles': { en: 'RBAC Roles', am: 'ኤርቢኤሲ ሚናዎች' },
  'admin.corporateEntities': { en: 'Corporate Entities', am: 'ድርጅታዊ አካላት' },
  'admin.rbacRolesRef': { en: 'RBAC Roles Reference', am: 'ኤርቢኤሲ ሚናዎች ማጣቀሻ' },
  'admin.searchCompany': { en: 'Search by company name or TIN...', am: 'በድርጅት ስም ወይም ቲአይኤን ፈልግ...' },
  'admin.noCorporateEntities': { en: 'No corporate entities found', am: 'ምንም ድርጅቶች አልተገኙም' },
  'admin.activate': { en: 'Activate', am: 'አንቃ' },
  'admin.suspend': { en: 'Suspend', am: 'አግድ' },
  'admin.tradeLicense': { en: 'Trade License', am: 'ንግድ ፈቃድ' },
  'admin.sector': { en: 'Sector', am: 'ሴክተር' },
  'admin.contact': { en: 'Contact', am: 'ግንኙነት' },
  'admin.rmAssigned': { en: 'RM Assigned', am: 'አርኤም ተመድቧል' },
  'admin.dailyLimit': { en: 'Daily Limit', am: 'ዕለታዊ ገደብ' },
  'admin.makerCheckerThreshold': { en: 'Maker-Checker Threshold', am: 'ሰሪ-አጣሪ ገደብ' },
  'admin.registered': { en: 'Registered', am: 'ተመዝግቧል' },
  'admin.approvedBy': { en: 'Approved By', am: 'ያፀደቀው' },
  'admin.addUser': { en: 'Add User', am: 'ተጠቃሚ ጨምር' },
  'admin.authorizedUsers': { en: 'Authorized Users', am: 'ስልጣን ያላቸው ተጠቃሚዎች' },
  'admin.noUsersYet': { en: 'No users added yet', am: 'ገና ተጠቃሚ አልተጨመረም' },
  'admin.selectCorporate': { en: 'Select a corporate entity to view details', am: 'ዝርዝሩን ለማየት ድርጅት ይምረጡ' },
  'admin.integrationHub': { en: 'Integration Hub', am: 'ውህደት ማዕከል' },
  'admin.manageIntegrations': { en: 'Manage external system integrations', am: 'ውጫዊ ስርዓት ውህደቶችን ያስተዳድሩ' },
  'admin.allCategories': { en: 'All Categories', am: 'ሁሉም ምድቦች' },
  'admin.searchIntegrations': { en: 'Search integrations...', am: 'ውህደቶችን ፈልግ...' },
  'admin.totalAssets': { en: 'Total Assets', am: 'ጠቅላላ ንብረቶች' },
  'admin.totalLiabilities': { en: 'Total Liabilities', am: 'ጠቅላላ ግዴታዎች' },
  'admin.totalIncome': { en: 'Total Income', am: 'ጠቅላላ ገቢ' },
  'admin.totalExpenses': { en: 'Total Expenses', am: 'ጠቅላላ ወጪዎች' },
  'admin.poolGLAccounts': { en: 'Pool GL Accounts', am: 'ፑል ጂኤል ሂሳቦች' },
  'admin.chartOfAccounts': { en: 'Chart of Accounts', am: 'ሂሳብ ዝርዝር' },
  'admin.generalLedger': { en: 'General Ledger', am: 'አጠቃላይ ደብተር' },
  'admin.glMappings': { en: 'GL Mappings', am: 'ጂኤል ግንኙነቶች' },
  'admin.feeDefinitions': { en: 'Fee Definitions', am: 'ክፍያ ትርጉሞች' },
  'admin.poolGLCBS': { en: 'Pool GL & CBS', am: 'ፑል ጂኤል እና ሲቢኤስ' },
  'admin.accountTree': { en: 'Account Tree', am: 'ሂሳብ ዛፍ' },
  'admin.balanceDist': { en: 'Balance Distribution', am: 'ቀሪ ስርጭት' },
  'admin.expandAll': { en: 'Expand All', am: 'ሁሉን ዘርጋ' },
  'admin.collapseAll': { en: 'Collapse All', am: 'ሁሉን ሰብስብ' },
  'admin.addAccount': { en: 'Add Account', am: 'ሂሳብ ጨምር' },
  'admin.addGLAccount': { en: 'Add GL Account', am: 'ጂኤል ሂሳብ ጨምር' },
  'admin.glCode': { en: 'GL Code', am: 'ጂኤል ኮድ' },
  'admin.accountType': { en: 'Account Type', am: 'ሂሳብ ዓይነት' },
  'admin.accountName': { en: 'Account Name', am: 'ሂሳብ ስም' },
  'admin.parentAccount': { en: 'Parent Account', am: 'ወላጅ ሂሳብ' },
  'admin.cbsCode': { en: 'CBS Code', am: 'ሲቢኤስ ኮድ' },
  'admin.poolGLAccount': { en: 'Pool GL Account', am: 'ፑል ጂኤል ሂሳብ' },
  'admin.description': { en: 'Description', am: 'መግለጫ' },
  'admin.createAccount': { en: 'Create Account', am: 'ሂሳብ ፍጠር' },
  'admin.suspended': { en: 'Suspended', am: 'ታግዷል' },
  'admin.corporateOnboardingTitle': { en: 'Corporate Onboarding', am: 'ድርጅት ማስተናገድ' },
  'admin.assignRBAC': { en: 'Register corporates, assign RBAC roles to employees', am: 'ድርጅቶችን ይመዝግቡ፣ ለሰራተኞች ኤርቢኤሲ ሚና ይስጡ' },
  'admin.rejectionReason': { en: 'Rejection Reason', am: 'ውድቅ ምክንያት' },

  // Internet Banking
  'ib.dashboard': { en: 'Dashboard', am: 'ዳሽቦርድ' },
  'ib.accounts': { en: 'Accounts', am: 'ሂሳቦች' },
  'ib.fundTransfers': { en: 'Fund Transfers', am: 'የገንዘብ ዝውውሮች' },
  'ib.beneficiaries': { en: 'Beneficiaries', am: 'ተጠቃሚዎች' },
  'ib.vendorPayments': { en: 'Vendor Payments', am: 'የአቅራቢ ክፍያዎች' },
  'ib.billPayments': { en: 'Bill Payments', am: 'ክፍያ መክፈያ' },
  'ib.salaryUpload': { en: 'Salary Upload', am: 'ደመወዝ ስቀል' },
  'ib.loanRepayments': { en: 'Loan Repayments', am: 'ብድር ክፍያ' },
  'ib.savingsFd': { en: 'Savings & FD', am: 'ቁጠባ እና ቋሚ ተቀማጭ' },
  'ib.scheduledPayments': { en: 'Scheduled Payments', am: 'የታቀዱ ክፍያዎች' },
  'ib.approvals': { en: 'Approvals', am: 'ፈቃዶች' },
  'ib.reports': { en: 'Reports', am: 'ሪፖርቶች' },
  'ib.statements': { en: 'Statements', am: 'መግለጫዎች' },
  'ib.messages': { en: 'Messages', am: 'መልእክቶች' },
  'ib.settings': { en: 'Settings', am: 'ቅንብሮች' },
  'ib.internetBanking': { en: 'Internet Banking', am: 'ኢንተርኔት ባንኪንግ' },
  'ib.welcomeUser': { en: 'Welcome', am: 'እንኳን ደህና መጡ' },
  'ib.financialOverview': { en: "Here's your financial overview", am: 'የእርስዎ የገንዘብ ማጠቃለያ' },
  'ib.totalBalance': { en: 'Total Balance', am: 'ጠቅላላ ቀሪ ሂሳብ' },
  'ib.activeAccounts': { en: 'Active Accounts', am: 'ንቁ ሂሳቦች' },
  'ib.nextEmiDue': { en: 'Next EMI Due', am: 'ቀጣይ EMI' },
  'ib.noActiveLoans': { en: 'No active loans', am: 'ንቁ ብድር የለም' },
  'ib.pendingApprovals': { en: 'Pending Approvals', am: 'በመጠባበቅ ላይ ያሉ ፈቃዶች' },
  'ib.actionRequired': { en: 'Action required', am: 'እርምጃ ያስፈልጋል' },
  'ib.unread': { en: 'unread', am: 'ያልተነበበ' },
  'ib.rmMessaging': { en: 'RM messaging', am: 'RM መልእክት' },
  'ib.exchangeRates': { en: 'Exchange Rates', am: 'ምንዛሬ ተመኖች' },
  'ib.loanPortfolio': { en: 'Loan Portfolio Summary', am: 'የብድር ፖርትፎሊዮ ማጠቃለያ' },
  'ib.totalOutstanding': { en: 'Total Outstanding', am: 'ጠቅላላ ቀሪ ብድር' },
  'ib.monthlyEmi': { en: 'Monthly EMI', am: 'ወርሃዊ EMI' },
  'ib.nextDue': { en: 'Next Due', am: 'ቀጣይ' },
  'ib.quickActions': { en: 'Quick Actions', am: 'ፈጣን እርምጃዎች' },
  'ib.recentTransactions': { en: 'Recent Transactions', am: 'የቅርብ ግብይቶች' },
  'ib.noRecentTx': { en: 'No recent transactions', am: 'የቅርብ ግብይቶች የሉም' },
  'ib.systemAnnouncement': { en: 'System Announcement', am: 'የስርዓት ማሳወቂያ' },
  'ib.announcementText': { en: 'Nisir Internet Banking now supports EthSwitch RTGS and TEFTNet ACH transfers to all Ethiopian banks. Fixed Deposit placement and Payroll bulk upload are available for corporate customers. Maker-Checker authorization is mandatory for transactions above 10,000 ETB.', am: 'ኒሲር ኢንተርኔት ባንኪንግ አሁን ለሁሉም የኢትዮጵያ ባንኮች EthSwitch RTGS እና TEFTNet ACH ዝውውሮችን ይደግፋል። ቋሚ ተቀማጭ እና የደመወዝ ባች ስቀል ለድርጅት ደንበኞች ይገኛል። ከ10,000 ብር በላይ ለሚሆኑ ግብይቶች ሜከር-ቼከር ፈቃድ ግዴታ ነው።' },
  'ib.goodMorning': { en: 'Good Morning', am: 'መልካም ጠዋት' },
  'ib.goodAfternoon': { en: 'Good Afternoon', am: 'መልካም ከሰዓት' },
  'ib.goodEvening': { en: 'Good Evening', am: 'መልካም ምሽት' },

  // IB Transfers
  'ib.transfer.ownAccount': { en: 'Own Account', am: 'የራስ ሂሳብ' },
  'ib.transfer.withinNisir': { en: 'Within Nisir', am: 'ኒሲር ውስጥ' },
  'ib.transfer.rtgs': { en: 'RTGS', am: 'RTGS' },
  'ib.transfer.rtgsDesc': { en: 'Real-Time Gross Settlement (>100K ETB)', am: 'የቅጽበት ጠቅላላ ማጣራት (>100ሺ ብር)' },
  'ib.transfer.ach': { en: 'ACH', am: 'ACH' },
  'ib.transfer.achDesc': { en: 'Automated Clearing House (next-day)', am: 'ራስ-ሰር ማጣራት (ቀጣይ ቀን)' },
  'ib.transfer.mobileWallet': { en: 'Mobile Wallet', am: 'ሞባይል ዋሌት' },
  'ib.transfer.mobileWalletDesc': { en: 'To Telebirr / M-Pesa wallet', am: 'ወደ ቴሌብር / ኤም-ፔሳ ዋሌት' },
  'ib.transfer.ownDesc': { en: 'Transfer between your own accounts', am: 'በሂሳቦችዎ መካከል ያዘዋውሩ' },
  'ib.transfer.internalDesc': { en: 'Transfer to another Nisir customer', am: 'ወደ ሌላ ኒሲር ደንበኛ ዝውውር' },
  'ib.transfer.sendSecurely': { en: 'Send money securely via multiple channels', am: 'በብዙ ቻናሎች ገንዘብ ደህንነቱ በተጠበቀ ሁኔታ ላክ' },
  'ib.transfer.successful': { en: 'Transfer Successful', am: 'ዝውውር ተሳክቷል' },
  'ib.transfer.newTransfer': { en: 'New Transfer', am: 'አዲስ ዝውውር' },
  'ib.transfer.fromAccount': { en: 'From Account', am: 'ከሂሳብ' },
  'ib.transfer.toAccount': { en: 'To Account', am: 'ወደ ሂሳብ' },
  'ib.transfer.selectSource': { en: 'Select source account', am: 'ምንጭ ሂሳብ ይምረጡ' },
  'ib.transfer.selectDest': { en: 'Select destination account', am: 'መድረሻ ሂሳብ ይምረጡ' },
  'ib.transfer.recipientPhone': { en: 'Recipient Phone (MSISDN)', am: 'የተቀባይ ስልክ (MSISDN)' },
  'ib.transfer.recipientName': { en: 'Recipient Name', am: 'የተቀባይ ስም' },
  'ib.transfer.bank': { en: 'Bank', am: 'ባንክ' },
  'ib.transfer.selectBank': { en: 'Select bank', am: 'ባንክ ይምረጡ' },
  'ib.transfer.accountNumber': { en: 'Account Number', am: 'የሂሳብ ቁጥር' },
  'ib.transfer.provider': { en: 'Provider', am: 'አቅራቢ' },
  'ib.transfer.phoneNumber': { en: 'Phone Number', am: 'ስልክ ቁጥር' },
  'ib.transfer.amountEtb': { en: 'Amount (ETB)', am: 'መጠን (ብር)' },
  'ib.transfer.description': { en: 'Description / Reason', am: 'መግለጫ / ምክንያት' },
  'ib.transfer.optional': { en: 'Optional', am: 'አማራጭ' },
  'ib.transfer.confirmTransfer': { en: 'Confirm Transfer', am: 'ዝውውር ያረጋግጡ' },
  'ib.transfer.verifyAndSend': { en: 'Verify & Send', am: 'አረጋግጥ እና ላክ' },

  // IB Bill Payments
  'ib.bill.title': { en: 'Bill Payments', am: 'ክፍያ መክፈያ' },
  'ib.bill.subtitle': { en: 'Pay utilities, taxes, and other bills', am: 'መገልገያ፣ ግብሮች እና ሌሎች ክፍያዎችን ይክፈሉ' },
  'ib.bill.paymentSuccessful': { en: 'Payment Successful', am: 'ክፍያ ተሳክቷል' },
  'ib.bill.payAnother': { en: 'Pay Another Bill', am: 'ሌላ ክፍያ ይክፈሉ' },
  'ib.bill.selectBiller': { en: 'Select Biller', am: 'ክፍያ ተቀባይ ይምረጡ' },
  'ib.bill.accountRef': { en: 'Bill Account / Reference Number', am: 'ክፍያ ሂሳብ / ማጣቀሻ ቁጥር' },
  'ib.bill.enterAccountNo': { en: 'Enter account number', am: 'የሂሳብ ቁጥር ያስገቡ' },
  'ib.bill.serviceFee': { en: 'Service fee', am: 'የአገልግሎት ክፍያ' },
  'ib.bill.verifyAndPay': { en: 'Verify & Pay', am: 'አረጋግጥ እና ክፈል' },
  'ib.bill.electricity': { en: 'Electricity', am: 'ኤሌክትሪክ' },
  'ib.bill.water': { en: 'Water', am: 'ውሃ' },
  'ib.bill.telecom': { en: 'Telecom', am: 'ቴሌኮም' },
  'ib.bill.education': { en: 'Education', am: 'ትምህርት' },
  'ib.bill.taxGov': { en: 'Tax / Gov', am: 'ግብር / መንግስት' },
  'ib.bill.other': { en: 'Other', am: 'ሌላ' },

  // IB Accounts
  'ib.accounts.myAccounts': { en: 'My Accounts', am: 'የእኔ ሂሳቦች' },
  'ib.accounts.manageAccounts': { en: 'View and manage all your accounts', am: 'ሁሉንም ሂሳቦችዎን ይመልከቱ እና ያስተዳድሩ' },
  'ib.accounts.totalAvailable': { en: 'Total Available Balance', am: 'ጠቅላላ ያለ ቀሪ ሂሳብ' },
  'ib.accounts.noTransactions': { en: 'No transactions', am: 'ግብይቶች የሉም' },
  'ib.accounts.currency': { en: 'Currency', am: 'ምንዛሬ' },
  'ib.accounts.interest': { en: 'Interest', am: 'ወለድ' },

  // IB Beneficiaries
  'ib.beneficiary.title': { en: 'Beneficiaries', am: 'ተጠቃሚዎች' },
  'ib.beneficiary.subtitle': { en: 'Manage saved payees for quick transfers', am: 'ለፈጣን ዝውውሮች የተቀመጡ ተቀባዮችን ያስተዳድሩ' },
  'ib.beneficiary.add': { en: 'Add Beneficiary', am: 'ተጠቃሚ ጨምር' },
  'ib.beneficiary.edit': { en: 'Edit Beneficiary', am: 'ተጠቃሚ አርም' },
  'ib.beneficiary.searchPlaceholder': { en: 'Search beneficiaries...', am: 'ተጠቃሚዎችን ፈልግ...' },
  'ib.beneficiary.noResults': { en: 'No beneficiaries found. Add one to get started.', am: 'ምንም ተጠቃሚ አልተገኘም። ለመጀመር ጨምር።' },
  'ib.beneficiary.transferType': { en: 'Transfer Type', am: 'የዝውውር ዓይነት' },
  'ib.beneficiary.nickname': { en: 'Nickname', am: 'ቅጽል ስም' },

  // IB Vendor Payments
  'ib.vendor.title': { en: 'Vendor Payments', am: 'የአቅራቢ ክፍያዎች' },
  'ib.vendor.subtitle': { en: 'Manage vendors and process payments with maker-checker', am: 'አቅራቢዎችን ያስተዳድሩ እና በሜከር-ቼከር ክፍያዎችን ያስኪዱ' },
  'ib.vendor.addVendor': { en: 'Add Vendor', am: 'አቅራቢ ጨምር' },
  'ib.vendor.vendors': { en: 'Vendors', am: 'አቅራቢዎች' },
  'ib.vendor.approvals': { en: 'Approvals', am: 'ፈቃዶች' },
  'ib.vendor.vendorName': { en: 'Vendor Name', am: 'የአቅራቢ ስም' },
  'ib.vendor.business': { en: 'Business', am: 'ንግድ' },
  'ib.vendor.totalPaid': { en: 'Total Paid', am: 'ጠቅላላ ክፍያ' },
  'ib.vendor.noVendors': { en: 'No vendors yet. Add a vendor to get started.', am: 'ምንም አቅራቢ የለም። ለመጀመር አቅራቢ ጨምር።' },
  'ib.vendor.noApprovals': { en: 'No approval requests', am: 'ምንም የፈቃድ ጥያቄ የለም' },
  'ib.vendor.payingTo': { en: 'Paying to', am: 'ክፍያ ወደ' },
  'ib.vendor.businessType': { en: 'Business Type', am: 'የንግድ ዓይነት' },
  'ib.vendor.scheduleDate': { en: 'Schedule Date (optional)', am: 'የክፍያ ቀን (አማራጭ)' },
  'ib.vendor.requireApproval': { en: 'Require Maker-Checker Approval', am: 'ሜከር-ቼከር ፈቃድ ያስፈልጋል' },
  'ib.vendor.submitForApproval': { en: 'Submit for Approval', am: 'ለፈቃድ አስገባ' },
  'ib.vendor.schedulePayment': { en: 'Schedule Payment', am: 'ክፍያ ቀጠሮ' },
  'ib.vendor.submittedBy': { en: 'Submitted by', am: 'ያስገባው' },
  'ib.vendor.approve': { en: 'Approve', am: 'ፍቀድ' },
  'ib.vendor.reject': { en: 'Reject', am: 'ከልክል' },

  // IB Salary
  'ib.salary.title': { en: 'Payroll & Salary Disbursement', am: 'ደመወዝ ክፍያ' },
  'ib.salary.subtitle': { en: 'Upload payroll CSV for bulk salary processing with maker-checker authorization', am: 'በሜከር-ቼከር ፈቃድ ለባች ደመወዝ ማስኬድ CSV ስቀል' },
  'ib.salary.template': { en: 'Payroll Template', am: 'ደመወዝ ቅጽ' },
  'ib.salary.newPayroll': { en: 'New Payroll', am: 'አዲስ ደመወዝ' },
  'ib.salary.uploadFile': { en: 'Upload Payroll File', am: 'የደመወዝ ፋይል ስቀል' },
  'ib.salary.batchName': { en: 'Batch / Payroll Name', am: 'ባች / ደመወዝ ስም' },
  'ib.salary.payrollMonth': { en: 'Payroll Month', am: 'ደመወዝ ወር' },
  'ib.salary.debitAccount': { en: 'Debit Account', am: 'ወጪ ሂሳብ' },
  'ib.salary.clickToUpload': { en: 'Click to upload payroll CSV', am: 'ደመወዝ CSV ለመስቀል ጠቅ ያድርጉ' },
  'ib.salary.employees': { en: 'Employees', am: 'ሰራተኞች' },
  'ib.salary.grossPay': { en: 'Gross Pay', am: 'ጠቅላላ ክፍያ' },
  'ib.salary.totalTax': { en: 'Total Tax', am: 'ጠቅላላ ግብር' },
  'ib.salary.totalPension': { en: 'Total Pension', am: 'ጠቅላላ ጡረታ' },
  'ib.salary.netDisbursement': { en: 'Net Disbursement', am: 'የተጣራ ክፍያ' },
  'ib.salary.payrollReview': { en: 'Payroll Review', am: 'ደመወዝ ግምገማ' },
  'ib.salary.submitForApproval': { en: 'Submit for Approval', am: 'ለፈቃድ አስገባ' },
  'ib.salary.processDirectly': { en: 'Process Directly', am: 'በቀጥታ አስኪድ' },
  'ib.salary.submittedForApproval': { en: 'Submitted for approval', am: 'ለፈቃድ ተልኳል' },
  'ib.salary.batchHistory': { en: 'Batch History', am: 'የባች ታሪክ' },
  'ib.salary.successful': { en: 'Successful', am: 'ተሳክቷል' },

  // IB Loan Repayments
  'ib.loan.title': { en: 'Loan Repayments', am: 'ብድር ክፍያ' },
  'ib.loan.subtitle': { en: 'View active loans and make repayments', am: 'ንቁ ብድሮችን ይመልከቱ እና ክፍያ ያድርጉ' },
  'ib.loan.noActiveLoans': { en: 'No active loans', am: 'ንቁ ብድር የለም' },
  'ib.loan.loanAmount': { en: 'Loan Amount', am: 'የብድር መጠን' },
  'ib.loan.outstanding': { en: 'Outstanding', am: 'ቀሪ ብድር' },
  'ib.loan.repaymentSchedule': { en: 'Repayment Schedule', am: 'ክፍያ መርሃ ግብር' },
  'ib.loan.makePayment': { en: 'Make Payment', am: 'ክፍያ ያድርጉ' },
  'ib.loan.dueDate': { en: 'Due Date', am: 'ክፍያ ቀን' },
  'ib.loan.principal': { en: 'Principal', am: 'ዋና ገንዘብ' },
  'ib.loan.interest': { en: 'Interest', am: 'ወለድ' },
  'ib.loan.paid': { en: 'Paid', am: 'ተከፍሏል' },
  'ib.loan.pay': { en: 'Pay', am: 'ክፈል' },
  'ib.loan.overdue': { en: 'overdue', am: 'ያለፈበት' },
  'ib.loan.repaid': { en: 'repaid', am: 'ተመልሷል' },
  'ib.loan.loanRepayment': { en: 'Loan Repayment', am: 'ብድር ክፍያ' },
  'ib.loan.confirmRepayment': { en: 'Confirm Repayment', am: 'ክፍያ ያረጋግጡ' },

  // IB Statements
  'ib.statement.title': { en: 'Account Statements', am: 'ሂሳብ መግለጫዎች' },
  'ib.statement.subtitle': { en: 'View and download transaction history', am: 'የግብይት ታሪክ ይመልከቱ እና ያውርዱ' },
  'ib.statement.account': { en: 'Account', am: 'ሂሳብ' },
  'ib.statement.fromDate': { en: 'From Date', am: 'ከቀን' },
  'ib.statement.toDate': { en: 'To Date', am: 'እስከ ቀን' },
  'ib.statement.totalCredits': { en: 'Total Credits', am: 'ጠቅላላ ገቢ' },
  'ib.statement.totalDebits': { en: 'Total Debits', am: 'ጠቅላላ ወጪ' },
  'ib.statement.transactions': { en: 'Transactions', am: 'ግብይቶች' },
  'ib.statement.exportCsv': { en: 'Export CSV', am: 'CSV ውጣ' },
  'ib.statement.debit': { en: 'Debit', am: 'ወጪ' },
  'ib.statement.credit': { en: 'Credit', am: 'ገቢ' },
  'ib.statement.selectAndGenerate': { en: 'Select filters and click Generate to view statement', am: 'ማጣሪያዎችን ይምረጡ እና መግለጫ ለማየት Generate ይጫኑ' },

  // IB Settings
  'ib.settings.title': { en: 'Settings', am: 'ቅንብሮች' },
  'ib.settings.subtitle': { en: 'Manage your profile and security', am: 'መገለጫዎን እና ደህንነትዎን ያስተዳድሩ' },
  'ib.settings.personalInfo': { en: 'Personal Information', am: 'ግላዊ መረጃ' },
  'ib.settings.changePassword': { en: 'Change Password', am: 'የይለፍ ቃል ቀይር' },
  'ib.settings.currentPassword': { en: 'Current Password', am: 'አሁን ያለ የይለፍ ቃል' },
  'ib.settings.newPassword': { en: 'New Password', am: 'አዲስ የይለፍ ቃል' },
  'ib.settings.confirmPassword': { en: 'Confirm New Password', am: 'አዲስ የይለፍ ቃል ያረጋግጡ' },
  'ib.settings.sessionSecurity': { en: 'Session Security', am: 'ክፍለ-ጊዜ ደህንነት' },
  'ib.settings.sessionStarted': { en: 'Session started', am: 'ክፍለ-ጊዜ ተጀምሯል' },
  'ib.settings.autoLogout': { en: 'Auto-logout: 15 minutes of inactivity', am: 'ራስ-ሰር ውጣ: 15 ደቂቃ ያለ እንቅስቃሴ' },
  'ib.settings.signOutAll': { en: 'Sign Out All Sessions', am: 'ሁሉንም ክፍለ-ጊዜ ውጣ' },
  'ib.settings.notifPrefs': { en: 'Notification Preferences', am: 'የማሳወቂያ ምርጫዎች' },
  'ib.settings.txAlerts': { en: 'Transaction Alerts', am: 'የግብይት ማሳወቂያ' },
  'ib.settings.txAlertsDesc': { en: 'Get notified for every debit/credit', am: 'ለእያንዳንዱ ወጪ/ገቢ ማሳወቂያ ያግኙ' },
  'ib.settings.loginAlerts': { en: 'Login Alerts', am: 'የመግቢያ ማሳወቂያ' },
  'ib.settings.loginAlertsDesc': { en: 'Alert on new device login', am: 'አዲስ መሣሪያ ሲገባ ማሳወቂያ' },
  'ib.settings.billReminders': { en: 'Bill Payment Reminders', am: 'ክፍያ ማስታወሻ' },
  'ib.settings.billRemindersDesc': { en: 'Remind before bill due dates', am: 'ክፍያ ከመድረሱ በፊት አስታውስ' },
  'ib.settings.salaryStatus': { en: 'Salary Batch Status', am: 'ደመወዝ ባች ሁኔታ' },
  'ib.settings.salaryStatusDesc': { en: 'Notify when batch is processed', am: 'ባች ሲያልቅ ማሳወቂያ' },
  'ib.settings.promos': { en: 'Promotional Offers', am: 'ማስተዋወቂያ' },
  'ib.settings.promosDesc': { en: 'Receive product offers and updates', am: 'ምርት ማስተዋወቂያ እና ዝመናዎች ይቀበሉ' },
  'ib.settings.updateProfile': { en: 'Update Profile', am: 'መገለጫ አዘምን' },
  'ib.settings.alternatePhone': { en: 'Alternate Phone', am: 'ተለዋጭ ስልክ' },

  // IB Approvals
  'ib.approval.title': { en: 'Maker-Checker Approvals', am: 'ሜከር-ቼከር ፈቃዶች' },
  'ib.approval.subtitle': { en: 'Review and authorize pending transactions', am: 'በመጠባበቅ ላይ ያሉ ግብይቶችን ይገምግሙ' },
  'ib.approval.pending': { en: 'Pending', am: 'በመጠባበቅ ላይ' },
  'ib.approval.history': { en: 'History', am: 'ታሪክ' },
  'ib.approval.noPending': { en: 'No pending approvals', am: 'በመጠባበቅ ላይ ያሉ ፈቃዶች የሉም' },
  'ib.approval.noHistory': { en: 'No history', am: 'ታሪክ የለም' },
  'ib.approval.remarks': { en: 'Remarks (optional)', am: 'አስተያየት (አማራጭ)' },
  'ib.approval.submitted': { en: 'Submitted', am: 'ቀርቧል' },
  'ib.approval.approvedBy': { en: 'Approved by', am: 'ያፀደቀው' },
  'ib.approval.rejectedBy': { en: 'Rejected by', am: 'ያልፈቀደው' },

  // IB Scheduled Payments
  'ib.scheduled.title': { en: 'Scheduled Payments', am: 'የታቀዱ ክፍያዎች' },
  'ib.scheduled.subtitle': { en: 'Set up one-time, weekly, or monthly auto-payments', am: 'ነጠላ፣ ሳምንታዊ ወይም ወርሃዊ ራስ-ሰር ክፍያ ያቅዱ' },
  'ib.scheduled.newSchedule': { en: 'New Schedule', am: 'አዲስ መርሃ ግብር' },
  'ib.scheduled.payee': { en: 'Payee', am: 'ተቀባይ' },
  'ib.scheduled.frequency': { en: 'Frequency', am: 'ድግግሞሽ' },
  'ib.scheduled.nextRun': { en: 'Next Run', am: 'ቀጣይ ሩጫ' },
  'ib.scheduled.noScheduled': { en: 'No scheduled payments. Create one to automate your payments.', am: 'ምንም የታቀደ ክፍያ የለም። ክፍያዎችን ለማሰማራት አንድ ይፍጠሩ።' },
  'ib.scheduled.schedulePayment': { en: 'Schedule Payment', am: 'ክፍያ ቀጠሮ' },
  'ib.scheduled.paymentType': { en: 'Payment Type', am: 'የክፍያ ዓይነት' },
  'ib.scheduled.fundTransfer': { en: 'Fund Transfer', am: 'ገንዘብ ዝውውር' },
  'ib.scheduled.salary': { en: 'Salary', am: 'ደመወዝ' },
  'ib.scheduled.oneTime': { en: 'One Time', am: 'ነጠላ' },
  'ib.scheduled.weekly': { en: 'Weekly', am: 'ሳምንታዊ' },
  'ib.scheduled.monthly': { en: 'Monthly', am: 'ወርሃዊ' },
  'ib.scheduled.payeeName': { en: 'Payee Name', am: 'የተቀባይ ስም' },
  'ib.scheduled.startDate': { en: 'Start Date', am: 'የመጀመሪያ ቀን' },
  'ib.scheduled.requiresApproval': { en: 'Requires Approval', am: 'ፈቃድ ያስፈልጋል' },
  'ib.scheduled.createSchedule': { en: 'Create Schedule', am: 'መርሃ ግብር ፍጠር' },
  'ib.scheduled.monthlyTotal': { en: 'Monthly Total', am: 'ወርሃዊ ጠቅላላ' },
  'ib.scheduled.paused': { en: 'Paused', am: 'ቆሟል' },

  // IB Savings & FD
  'ib.savings.title': { en: 'Savings & Fixed Deposits', am: 'ቁጠባ እና ቋሚ ተቀማጭ' },
  'ib.savings.subtitle': { en: 'Manage savings accounts and term deposits', am: 'የቁጠባ ሂሳቦችን እና ቋሚ ተቀማጮችን ያስተዳድሩ' },
  'ib.savings.newFD': { en: 'New Fixed Deposit', am: 'አዲስ ቋሚ ተቀማጭ' },
  'ib.savings.totalSavings': { en: 'Total Savings', am: 'ጠቅላላ ቁጠባ' },
  'ib.savings.fixedDeposits': { en: 'Fixed Deposits', am: 'ቋሚ ተቀማጮች' },
  'ib.savings.interestEarned': { en: 'Interest Earned', am: 'የተገኘ ወለድ' },
  'ib.savings.activeFDs': { en: 'Active FDs', am: 'ንቁ ቋሚ ተቀማጮች' },
  'ib.savings.savingsAccounts': { en: 'Savings Accounts', am: 'ቁጠባ ሂሳቦች' },
  'ib.savings.noSavings': { en: 'No savings accounts', am: 'ቁጠባ ሂሳብ የለም' },
  'ib.savings.noFD': { en: 'No Fixed Deposits', am: 'ቋሚ ተቀማጭ የለም' },
  'ib.savings.placeFD': { en: 'Place FD Now', am: 'አሁን ቋሚ ተቀማጭ ያስቀምጡ' },
  'ib.savings.placeFDTitle': { en: 'Place Fixed Deposit', am: 'ቋሚ ተቀማጭ ያስቀምጡ' },
  'ib.savings.fromAccount': { en: 'From Account', am: 'ከሂሳብ' },
  'ib.savings.tenure': { en: 'Tenure', am: 'ጊዜ' },
  'ib.savings.maturityInstruction': { en: 'Maturity Instruction', am: 'ማብቂያ መመሪያ' },
  'ib.savings.maturityValue': { en: 'Maturity Value', am: 'ማብቂያ ዋጋ' },
  'ib.savings.daysRemaining': { en: 'Days Remaining', am: 'ቀሪ ቀናት' },
  'ib.savings.maturityDate': { en: 'Maturity Date', am: 'ማብቂያ ቀን' },
  'ib.savings.accruedInterest': { en: 'Accrued Interest', am: 'የተከማቸ ወለድ' },
  'ib.savings.mtdInterest': { en: 'Month-to-Date Interest', am: 'ወር-እስከ-ዛሬ ወለድ' },

  // IB Cash Management & Reports
  'ib.reports.title': { en: 'Cash Management & Reports', am: 'ጥሬ ገንዘብ አስተዳደር እና ሪፖርቶች' },
  'ib.reports.subtitle': { en: 'Daily position, cash flow analysis, payroll & loan portfolio reports', am: 'ቀን አቋም፣ ገንዘብ ፍሰት ትንተና፣ ደመወዝ እና ብድር ሪፖርቶች' },
  'ib.reports.dailyPosition': { en: 'Daily Position', am: 'ቀን አቋም' },
  'ib.reports.cashFlow': { en: 'Cash Flow', am: 'ገንዘብ ፍሰት' },
  'ib.reports.payroll': { en: 'Payroll', am: 'ደመወዝ' },
  'ib.reports.loanPortfolio': { en: 'Loan Portfolio', am: 'ብድር ፖርትፎሊዮ' },
  'ib.reports.netCashPosition': { en: 'Net Cash Position', am: 'ጠቅላላ ጥሬ ገንዘብ አቋም' },
  'ib.reports.todayCredits': { en: "Today's Credits", am: 'የዛሬ ገቢ' },
  'ib.reports.todayDebits': { en: "Today's Debits", am: 'የዛሬ ወጪ' },
  'ib.reports.accountPositions': { en: 'Account Positions', am: 'የሂሳብ አቋም' },
  'ib.reports.upcomingObligations': { en: 'Upcoming Obligations', am: 'ቀጣይ ግዴታዎች' },
  'ib.reports.monthlyEmiLoans': { en: 'Monthly EMI (Loans)', am: 'ወርሃዊ EMI (ብድሮች)' },
  'ib.reports.scheduledPayments': { en: 'Scheduled Payments', am: 'የታቀዱ ክፍያዎች' },
  'ib.reports.netAfterObligations': { en: 'Net After Obligations', am: 'ከግዴታዎች በኋላ' },
  'ib.reports.monthCredits': { en: 'Month Credits', am: 'ወር ገቢ' },
  'ib.reports.monthDebits': { en: 'Month Debits', am: 'ወር ወጪ' },
  'ib.reports.netFlow': { en: 'Net Flow', am: 'ጠቅላላ ፍሰት' },
  'ib.reports.txBreakdown': { en: 'Transaction Breakdown (This Month)', am: 'ግብይት ዝርዝር (ይህ ወር)' },
  'ib.reports.txType': { en: 'Transaction Type', am: 'ግብይት ዓይነት' },
  'ib.reports.count': { en: 'Count', am: 'ቁጥር' },
  'ib.reports.totalDebit': { en: 'Total Debit', am: 'ጠቅላላ ወጪ' },
  'ib.reports.totalCredit': { en: 'Total Credit', am: 'ጠቅላላ ገቢ' },
  'ib.reports.noPayrollHistory': { en: 'No payroll history', am: 'ደመወዝ ታሪክ የለም' },
  'ib.reports.batchName': { en: 'Batch Name', am: 'ባች ስም' },
  'ib.reports.totalDebtOutstanding': { en: 'Total Debt Outstanding', am: 'ጠቅላላ ቀሪ ብድር' },
  'ib.reports.monthlyEmiObligation': { en: 'Monthly EMI Obligation', am: 'ወርሃዊ EMI ግዴታ' },
  'ib.reports.debtToBalance': { en: 'Debt-to-Balance Ratio', am: 'ብድር ለ-ቀሪ ጥምርታ' },

  // IB Messages & Support
  'ib.msg.title': { en: 'Messages & Support', am: 'መልእክቶች እና ድጋፍ' },
  'ib.msg.subtitle': { en: 'Secure messaging with your Relationship Manager', am: 'ከ Relationship Manager ጋር ደህንነቱ የተጠበቀ መልእክት' },
  'ib.msg.requestCallback': { en: 'Request Callback', am: 'ጥሪ ጠይቅ' },
  'ib.msg.newMessage': { en: 'New Message', am: 'አዲስ መልእክት' },
  'ib.msg.faq': { en: 'FAQ', am: 'ተደጋጋሚ ጥያቄዎች' },
  'ib.msg.noMessages': { en: 'No messages yet', am: 'ምንም መልእክት የለም' },
  'ib.msg.startConversation': { en: 'Start Conversation', am: 'ውይይት ጀምር' },
  'ib.msg.sendToRM': { en: 'Send a secure message to your Relationship Manager', am: 'ወደ Relationship Manager ደህንነቱ የተጠበቀ መልእክት ላክ' },
  'ib.msg.backToMessages': { en: 'Back to messages', am: 'ወደ መልእክቶች ተመለስ' },
  'ib.msg.typeReply': { en: 'Type your reply...', am: 'መልስዎን ያስገቡ...' },
  'ib.msg.responseTime': { en: 'Expected response time: Within 4 business hours', am: 'የሚጠበቅ ምላሽ ጊዜ: በ4 ስራ ሰዓት ውስጥ' },
  'ib.msg.newSecureMsg': { en: 'New Secure Message', am: 'አዲስ ደህንነቱ የተጠበቀ መልእክት' },
  'ib.msg.category': { en: 'Category', am: 'ምድብ' },
  'ib.msg.subject': { en: 'Subject', am: 'ርዕስ' },
  'ib.msg.message': { en: 'Message', am: 'መልእክት' },
  'ib.msg.sendMessage': { en: 'Send Message', am: 'መልእክት ላክ' },
  'ib.msg.callbackTitle': { en: 'Request Callback', am: 'ጥሪ ጠይቅ' },
  'ib.msg.preferredTime': { en: 'Preferred Time', am: 'ተመራጭ ጊዜ' },
  'ib.msg.submitRequest': { en: 'Submit Request', am: 'ጥያቄ አስገባ' },
  'ib.msg.searchFaq': { en: 'Search FAQ...', am: 'ተደጋጋሚ ጥያቄ ፈልግ...' },
  'ib.msg.businessHours': { en: 'Business hours: Mon–Sat, 8:00 AM – 6:00 PM EAT', am: 'ስራ ሰዓት: ሰኞ–ቅዳሜ, 8:00 – 6:00 EAT' },
  'ib.msg.rmResponseTime': { en: 'Your RM will respond within 4 business hours (Mon–Sat, 8AM–6PM EAT)', am: 'RM ዎ በ4 ስራ ሰዓት ውስጥ ምላሽ ይሰጣል' },
  'ib.msg.you': { en: 'You', am: 'እርስዎ' },
  'ib.msg.relationshipManager': { en: 'Relationship Manager', am: 'Relationship Manager' },
  'ib.msg.transactionQuery': { en: 'Transaction Query', am: 'ግብይት ጥያቄ' },
  'ib.msg.loanQuery': { en: 'Loan Query', am: 'ብድር ጥያቄ' },
  'ib.msg.accountQuery': { en: 'Account Query', am: 'ሂሳብ ጥያቄ' },
  'ib.msg.complaint': { en: 'Complaint', am: 'ቅሬታ' },
  'ib.msg.dispute': { en: 'Transaction Dispute', am: 'ግብይት ክርክር' },
  'ib.msg.generalInquiry': { en: 'General Inquiry', am: 'ጠቅላላ ጥያቄ' },

  // 404
  'notFound.title': { en: 'Page not found', am: 'ገጹ አልተገኘም' },
  'notFound.message': { en: 'Oops! Page not found', am: 'ይቅርታ! ገጹ አልተገኘም' },
  'notFound.returnHome': { en: 'Return to Home', am: 'ወደ መነሻ ተመለስ' },

  // Loan Calculator
  'loan.principal': { en: 'Principal', am: 'ዋና ገንዘብ' },
  'loan.interest': { en: 'Interest', am: 'ወለድ' },
  'loan.months': { en: 'months', am: 'ወራት' },
  'loan.month': { en: 'month', am: 'ወር' },
  'loan.monthlyPayment': { en: 'Monthly Payment', am: 'ወርሃዊ ክፍያ' },
  'loan.totalInterest': { en: 'Total Interest', am: 'ጠቅላላ ወለድ' },
  'loan.totalPayable': { en: 'Total Payable', am: 'ጠቅላላ ክፍያ' },

  // Regulatory Reporting Engine
  'report.complianceReports': { en: 'Compliance & Regulatory Reports', am: 'ተገዢነት እና ቁጥጥር ሪፖርቶች' },
  'report.nbeRegulatoryEngine': { en: 'NBE Regulatory Reporting Engine', am: 'የኢትዮጵያ ብሔራዊ ባንክ ቁጥጥር ሪፖርት ሞተር' },
  'report.customersInScope': { en: 'Customers in Scope', am: 'በወሰን ውስጥ ያሉ ደንበኞች' },
  'report.registry': { en: 'Report Registry', am: 'ሪፖርት መዝገብ' },
  'report.totalReports': { en: 'Total Reports', am: 'ጠቅላላ ሪፖርቶች' },
  'report.submitted': { en: 'Submitted', am: 'የቀረበ' },
  'report.pending': { en: 'Pending', am: 'በመጠባበቅ ላይ' },
  'report.overdue': { en: 'Overdue', am: 'ያለፈበት' },
  'report.nbeRegulatoryReturns': { en: 'NBE Regulatory Returns', am: 'የኢትዮጵያ ብሔራዊ ባንክ ቁጥጥር ተመላሾች' },
  'report.businessIntelligence': { en: 'Business Intelligence Reports', am: 'የንግድ ዘርፍ ሪፖርቶች' },
  'report.code': { en: 'Code', am: 'ኮድ' },
  'report.reportName': { en: 'Report Name', am: 'የሪፖርት ስም' },
  'report.frequency': { en: 'Frequency', am: 'ድግግሞሽ' },
  'report.directive': { en: 'Directive', am: 'መመሪያ' },
  'report.deadline': { en: 'Deadline', am: 'የማቅረቢያ ጊዜ' },
  'report.status': { en: 'Status', am: 'ሁኔታ' },
  'report.validation': { en: 'Validation', am: 'ማረጋገጫ' },
  'report.actions': { en: 'Actions', am: 'ተግባሮች' },
  'report.view': { en: 'View', am: 'ይመልከቱ' },
  'report.lastGenerated': { en: 'Last Generated', am: 'የመጨረሻ ጊዜ የተፈጠረ' },
  'report.exportAll': { en: 'Export All', am: 'ሁሉንም ወደ ውጭ ላክ' },
  'report.generateQuarterly': { en: 'Generate Quarterly', am: 'ሩብ ዓመታዊ አመንጭ' },
  'report.balanceSheet': { en: 'Balance Sheet (Statement of Financial Position)', am: 'ሚዛን ሉህ (የፋይናንስ አቋም መግለጫ)' },
  'report.periodEnding': { en: 'Period Ending', am: 'የጊዜ ማብቂያ' },
  'report.assets': { en: 'Assets', am: 'ንብረቶች' },
  'report.liabilities': { en: 'Liabilities', am: 'ዕዳዎች' },
  'report.equity': { en: 'Equity', am: 'ካፒታል' },
  'report.incomeStatement': { en: 'Income Statement (Profit & Loss)', am: 'የገቢ መግለጫ (ትርፍ እና ኪሳራ)' },
  'report.description': { en: 'Description', am: 'ማብራሪያ' },
  'report.nbeCategory': { en: 'NBE Category', am: 'የኢ.ብ.ባ ምድብ' },
  'report.amountETB': { en: 'Amount (ETB)', am: 'መጠን (ብር)' },
  'report.loanPortfolioAssetQuality': { en: 'Loan Portfolio & Asset Quality (5-Grade)', am: 'የብድር ፖርትፎሊዮ እና የንብረት ጥራት (5-ደረጃ)' },
  'report.grade': { en: 'Grade', am: 'ደረጃ' },
  'report.classification': { en: 'Classification', am: 'ምድብ' },
  'report.loanCount': { en: 'Loans', am: 'ብድሮች' },
  'report.outstanding': { en: 'Outstanding (ETB)', am: 'ቀሪ (ብር)' },
  'report.provisionRate': { en: 'Prov. Rate', am: 'የመጠባበቂያ ምጣኔ' },
  'report.requiredProvision': { en: 'Required Provision', am: 'የሚፈለግ መጠባበቂያ' },
  'report.total': { en: 'Total', am: 'ጠቅላላ' },
  'report.byProduct': { en: 'By Product Type', am: 'በምርት ዓይነት' },
  'report.product': { en: 'Product', am: 'ምርት' },
  'report.ageingSchedule': { en: 'Ageing Schedule', am: 'የዕድሜ ሰሌዳ' },
  'report.capitalAdequacy': { en: 'Capital Adequacy Return (CAR)', am: 'የካፒታል በቂነት ተመላሽ' },
  'report.qualifyingCapital': { en: 'Qualifying Capital', am: 'ብቁ ካፒታል' },
  'report.totalRWA': { en: 'Total Risk-Weighted Assets', am: 'ጠቅላላ በአደጋ የተመዘነ ንብረት' },
  'report.carRatio': { en: 'CAR Ratio', am: 'የካፒታል በቂነት ምጣኔ' },
  'report.assetCategory': { en: 'Asset Category', am: 'የንብረት ምድብ' },
  'report.bookValue': { en: 'Book Value', am: 'የመጽሐፍ ዋጋ' },
  'report.riskWeight': { en: 'Risk Weight', am: 'የአደጋ ክብደት' },
  'report.liquidityReturn': { en: 'Liquidity Return', am: 'የፈሳሽነት ተመላሽ' },
  'report.liquidAssets': { en: 'Liquid Assets', am: 'ፈሳሽ ንብረቶች' },
  'report.totalDeposits': { en: 'Total Deposits', am: 'ጠቅላላ ተቀማጭ' },
  'report.liquidityRatio': { en: 'Liquidity Ratio', am: 'የፈሳሽነት ምጣኔ' },
  'report.maturityGapAnalysis': { en: 'Maturity Gap Analysis', am: 'የብስለት ክፍተት ትንተና' },
  'report.maturityBucket': { en: 'Maturity Bucket', am: 'የብስለት ክፍለ ጊዜ' },
  'report.agentNetworkActivity': { en: 'Agent Network Activity Report', am: 'የወኪል አውታረ መረብ እንቅስቃሴ ሪፖርት' },
  'report.agent': { en: 'Agent', am: 'ወኪል' },
  'report.category': { en: 'Category', am: 'ምድብ' },
  'report.location': { en: 'Location', am: 'አድራሻ' },
  'report.flags': { en: 'Flags', am: 'ማስጠንቀቂያዎች' },
  'report.kycTierStats': { en: 'KYC Tier & Account Opening Statistics', am: 'የ KYC ደረጃ እና ሂሳብ ክፍት ስታቲስቲክስ' },
  'report.kycTier': { en: 'KYC Tier', am: 'የ KYC ደረጃ' },
  'report.activeCustomers': { en: 'Active Customers', am: 'ንቁ ደንበኞች' },
  'report.newAccounts': { en: 'New Accounts', am: 'አዲስ ሂሳቦች' },
  'report.limitBreaches': { en: 'Limit Breaches', am: 'የገደብ ጥሰቶች' },
  'report.pendingUpgrades': { en: 'Pending Upgrades', am: 'በመጠባበቅ ላይ ያሉ ማሻሻያዎች' },
  'report.docsVerified': { en: 'Docs Verified', am: 'የተረጋገጡ ሰነዶች' },
  'report.docsRejected': { en: 'Docs Rejected', am: 'የተቀሩ ሰነዶች' },
  'report.customerDistByRegion': { en: 'Customer Distribution by Region', am: 'በክልል የደንበኞች ስርጭት' },
  'report.region': { en: 'Region', am: 'ክልል' },
  'report.dfsTransactionReport': { en: 'Digital Financial Services Transaction Report', am: 'የዲጂታል ፋይናንሺያል አገልግሎቶች ግብይት ሪፖርት' },
  'report.transactionType': { en: 'Transaction Type', am: 'የግብይት ዓይነት' },
  'report.count': { en: 'Count', am: 'ብዛት' },
  'report.valueETB': { en: 'Value (ETB)', am: 'ዋጋ (ብር)' },
  'report.feesETB': { en: 'Fees (ETB)', am: 'ክፍያዎች (ብር)' },
  'report.uniqueUsers': { en: 'Unique Users', am: 'ልዩ ተጠቃሚዎች' },
  'report.successRate': { en: 'Success %', am: 'የስኬት %' },
  'report.nfisInclusion': { en: 'NFIS-II Financial Inclusion Metrics', am: 'NFIS-II የፋይናንስ ማካተት መለኪያዎች' },
  'report.savingsMobilisation': { en: 'Savings Mobilisation Schedule', am: 'የቁጠባ ማሰባሰቢያ ሰሌዳ' },
  'report.accountType': { en: 'Account Type', am: 'የሂሳብ ዓይነት' },
  'report.interestRate': { en: 'Interest Rate', am: 'የወለድ ምጣኔ' },
  'report.largeExposure': { en: 'Large Exposure Report', am: 'ትልቅ ተጋላጭነት ሪፖርት' },
  'report.borrowerName': { en: 'Borrower Name', am: 'የተበዳሪ ስም' },
  'report.totalExposure': { en: 'Total Exposure (ETB)', am: 'ጠቅላላ ተጋላጭነት (ብር)' },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('nisir-language');
    return (saved === 'am' ? 'am' : 'en') as Language;
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('nisir-language', lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[key]?.[language] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
